import { Creator, User, Order } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_brand_01',
    name: 'Elena Rostova',
    email: 'elena@aura-cosmetics.com',
    role: 'brand',
    companyName: 'Aura Skincare Paris',
    avatar: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
    location: 'Berlin & Paris',
    website: 'https://aura-skincare.com',
    industry: 'Beauty, Cosmetics & Wellness',
    bio: 'Brand Lead at Aura Skincare developing organic beauty and wellness product launches.',
    balanceEur: 8450,
  },
  {
    id: 'user_creator_01',
    name: 'Sophie Kim',
    email: 'sophie@sophiekim.com',
    phone: '+1 (555) 234-5678',
    role: 'creator',
    handle: '@sophiekim',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    location: 'Los Angeles, CA',
    bio: 'I create authentic, relatable content about beauty, wellness and everyday life. I love working with brands that share my values and believe in meaningful, long-term partnerships.',
    balanceEur: 3200,
  },
];

export const MOCK_CREATORS: Creator[] = [
  {
    id: 'creator-01',
    name: 'Sophie Kim',
    handle: 'sophiekim',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    bio: 'I create authentic, relatable content about beauty, wellness and everyday life. I love working with brands that share my values and believe in meaningful, long-term partnerships.',
    location: 'Los Angeles, CA',
    contactEmail: 'collabs@sophiekim.com',
    contactPhone: '+1 (555) 234-5678',
    verified: true,
    languages: ['English', 'French'],
    collaborationPreferences: ['sponsored', 'ugc', 'reviews', 'ambassador'],
    city: 'Los Angeles',
    country: 'United States',
    categories: ['Beauty', 'Lifestyle', 'Fashion'],
    tags: ['Beauty', 'Lifestyle', 'Self Care', 'Skincare', 'Wellness'],
    platforms: {
      instagram: {
        followers: 1200000,
        followersFormatted: '1.2M',
        handle: '@sophiekim',
        engagementRate: '4.8%',
        avgViews: '240K',
        url: 'https://instagram.com/sophiekim',
      },
      tiktok: {
        followers: 680000,
        followersFormatted: '680K',
        handle: '@sophie.kim',
        engagementRate: '6.2%',
        avgViews: '410K',
        url: 'https://tiktok.com/@sophie.kim',
      },
      youtube: {
        followers: 210000,
        followersFormatted: '210K',
        handle: 'Sophie Kim Vlogs',
        engagementRate: '8.4%',
        avgViews: '95K',
        url: 'https://youtube.com/@sophiekimvlogs',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: '48h Rush Available',
      },
    },
    startingPriceEur: 500,
    rating: 4.98,
    reviewsCount: 42,
    totalCollaborations: 128,
    packages: [
      {
        id: 'pkg-sk-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Dedicated Shortform Video (Reel / TikTok)',
        type: 'reel',
        description: '1x High-retention 60s vertical video feature tailored for Instagram Reels and TikTok with authentic product demo.',
        priceEur: 850,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: [
          '1x 60s Dedicated 4K Video',
          'Instagram Reel + TikTok Audio Sync',
          'Product Tagging & Bio Link',
          '30-Day Organic Rights',
        ],
      },
      {
        id: 'pkg-sk-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Reel + Story Sequence Bundle',
        type: 'bundle',
        description: 'Our highest-converting organic partnership: 1x 4K Reel plus 3x interactive Stories with direct swipe-up link stickers and Spark ad whitelisting.',
        priceEur: 1450,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Spark Ad Whitelisting',
        inclusions: [
          '1x 60s Dedicated 4K Reel',
          '3x Story Sequence with Link Stickers',
          'TikTok Cross-Posting & Audio Whitelist',
          '60-Day Spark Ad Authorization Code',
        ],
      },
      {
        id: 'pkg-sk-omni',
        platform: 'all',
        platforms: ['youtube', 'instagram', 'tiktok'],
        title: '360° All-Platform Brand Takeover',
        type: 'bundle',
        description: 'Complete cross-channel launch bundle across YouTube, Instagram, and TikTok with organic cross-posts and high-conversion ad rights.',
        priceEur: 3200,
        deliveryDays: 7,
        revisions: 2,
        usageRights: '90-Day Full Commercial Ad Rights',
        inclusions: [
          '1x YouTube Dedicated Integration (60-90s)',
          '1x 60s Instagram Reel (4K) + 3x Stories',
          '1x High-Retention TikTok Hook Video',
          '90-Day Full Commercial Ad Whitelisting',
          'Cross-Platform Performance Analytics',
        ],
      },
    ],
    portfolio: [
      {
        id: 'port-1',
        brandName: 'Laneige',
        brandLogo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Dewy Glaze Hydration Routine Reel',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
        views: '320K',
        likes: '28.4K',
        comments: '1,240',
        shares: '6,800',
        engagementRate: '8.9%',
        duration: '0:45',
        aspectRatio: '9:16',
        platform: 'instagram',
        deliverableType: '60s 4K Reel with Voiceover',
        description: 'Demonstrated 3-step morning hydration glaze routine featuring Laneige Water Bank Serum with authentic skin texture closeups and natural lighting.',
        soundTrack: 'Original Audio • Sophie Kim (Trending Beauty Tone)',
        completedDate: 'February 2026',
        packagePriceEur: 1200,
      },
      {
        id: 'port-1b',
        brandName: 'Gisou',
        brandLogo: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Honey Infused Hair Glow Story Series',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
        views: '240K',
        likes: '19.8K',
        comments: '890',
        shares: '4,100',
        engagementRate: '7.6%',
        duration: '0:30',
        aspectRatio: '9:16',
        platform: 'instagram',
        deliverableType: '3x Story Sequence with Link Sticker',
        description: 'Multi-part interactive Story sequence featuring Gisou Honey Hair Oil with direct swipe-up discount sticker and before/after shine results.',
        soundTrack: 'Aesthetic Chill Beat • Gisou Official',
        completedDate: 'January 2026',
        packagePriceEur: 500,
      },
      {
        id: 'port-1c',
        brandName: 'Summer Fridays',
        brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Jet Lag Mask Travel Prep Carousel',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
        views: '195K',
        likes: '16.2K',
        comments: '720',
        shares: '3,200',
        engagementRate: '6.8%',
        aspectRatio: '1:1',
        platform: 'instagram',
        deliverableType: '4-Slide High-Res Carousel Post',
        description: 'Curated 4-slide Instagram Carousel showing in-flight hydration routine, packaging aesthetics, and step-by-step application instructions.',
        completedDate: 'December 2025',
        packagePriceEur: 800,
      },
      {
        id: 'port-2',
        brandName: 'The Ordinary',
        brandLogo: 'https://images.unsplash.com/photo-1608248597359-53530f2955cf?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Barrier Repair 3-Step TikTok Spark Ad',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1608248597359-53530f2955cf?auto=format&fit=crop&w=800&q=80',
        views: '410K',
        likes: '34.1K',
        comments: '2,450',
        shares: '12,300',
        engagementRate: '9.4%',
        duration: '0:35',
        aspectRatio: '9:16',
        platform: 'tiktok',
        deliverableType: '30s High-Conversion Spark Ad',
        description: 'Fast-paced hook testing the viral Soothing & Barrier Support Serum on sensitized skin. Generated a verified 4.2x ROAS in brand Spark Ad campaigns.',
        soundTrack: 'Trending Skincare Sound • Viral Pop Beat',
        completedDate: 'February 2026',
        packagePriceEur: 1350,
      },
      {
        id: 'port-2b',
        brandName: 'CeraVe',
        brandLogo: 'https://images.unsplash.com/photo-1556228722-d95a5f118126?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Nighttime Double Cleansing Routine',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1556228722-d95a5f118126?auto=format&fit=crop&w=800&q=80',
        views: '385K',
        likes: '29.8K',
        comments: '1,620',
        shares: '8,400',
        engagementRate: '8.1%',
        duration: '0:40',
        aspectRatio: '9:16',
        platform: 'tiktok',
        deliverableType: 'Dedicated TikTok Video with Pinned Comment',
        description: 'Dermatologist-recommended cleansing routine comparing oil vs foaming cleanser with macro camera texture shots.',
        soundTrack: 'ASMR Water Sounds & Voiceover',
        completedDate: 'January 2026',
        packagePriceEur: 950,
      },
      {
        id: 'port-3',
        brandName: 'Sephora Paris',
        brandLogo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'A Day in My Life & Skincare Shelf Tour',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
        views: '540K',
        likes: '49.2K',
        comments: '3,810',
        shares: '15,600',
        engagementRate: '10.2%',
        duration: '11:45',
        aspectRatio: '16:9',
        platform: 'youtube',
        deliverableType: 'Full Dedicated 12-Min YouTube Review',
        description: 'Comprehensive 4K vanity makeover and top 5 French pharmacy beauty discoveries with affiliate tracking links in top pinned comment.',
        soundTrack: 'Lofi Bedroom Beats • Permanent License',
        completedDate: 'February 2026',
        packagePriceEur: 3200,
      },
      {
        id: 'port-3b',
        brandName: 'Dyson Beauty',
        brandLogo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Airwrap Multi-Styler Morning Routine',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
        views: '390K',
        likes: '31.0K',
        comments: '1,950',
        shares: '9,200',
        engagementRate: '8.7%',
        duration: '1:30',
        aspectRatio: '16:9',
        platform: 'youtube',
        deliverableType: '90s Dedicated Mid-Roll Integration',
        description: 'Seamless mid-roll segment showing the Coanda smoothing effect and quick blowout tips with dedicated discount code banner.',
        completedDate: 'January 2026',
        packagePriceEur: 1800,
      },
      {
        id: 'port-4',
        brandName: 'OUAI',
        brandLogo: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Hair & Body Mist Direct-Response UGC Pack',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
        views: '280K',
        likes: '21.9K',
        comments: '940',
        shares: '5,300',
        engagementRate: '7.9%',
        duration: '0:25',
        aspectRatio: '9:16',
        platform: 'ugc',
        deliverableType: '2x 9:16 Hook Variations for Meta Ads',
        description: 'Raw iPhone 15 Pro 4K UGC creatives filmed in natural bathroom lighting with captions, sound effects, and clear call-to-action hooks.',
        completedDate: 'February 2026',
        packagePriceEur: 650,
      },
      {
        id: 'port-4b',
        brandName: 'Glossier',
        brandLogo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Balm Dotcom Honest Reaction UGC Ad Set',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
        views: '340K',
        likes: '26.5K',
        comments: '1,120',
        shares: '7,100',
        engagementRate: '8.3%',
        duration: '0:30',
        aspectRatio: '9:16',
        platform: 'ugc',
        deliverableType: '3x Full 9:16 Direct Response UGC Creatives',
        description: 'Problem-solution UGC video ads demonstrating lip hydration, non-sticky formula, and subtle tint in 4K resolution.',
        completedDate: 'December 2025',
        packagePriceEur: 1100,
      },
    ],
    photos: [
      {
        id: 'photo-sk-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Commercial Beauty Headshot • Studio Natural Lighting',
        category: 'headshot',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Los Angeles, CA',
        cameraGear: 'Sony A7R V • 85mm f/1.4 GM',
        tags: ['Clean Beauty', 'Natural Makeup', 'High-Res Headshot'],
      },
      {
        id: 'photo-sk-2',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fashion Week Streetstyle Look • Paris Fashion Week',
        category: 'lifestyle',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Paris, France',
        cameraGear: 'Leica Q3 • 28mm Summilux',
        tags: ['Streetwear', 'High Fashion', 'Urban Lifestyle'],
      },
      {
        id: 'photo-sk-3',
        url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=85',
        caption: 'Morning Skincare Routine • Golden Hour Aesthetic',
        category: 'modeling',
        aspectRatio: 'landscape',
        date: 'February 2026',
        location: 'Venice Beach Studio',
        cameraGear: 'Canon EOS R5 • 50mm f/1.2L',
        tags: ['Skincare Glow', 'Morning Routine', 'Dewy Skin'],
      },
      {
        id: 'photo-sk-4',
        url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=85',
        caption: 'BTS Content Production Setup & 4K Camera Rig',
        category: 'bts',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Creative Suite Los Angeles',
        cameraGear: 'Sony FX3 Cinema Rig',
        tags: ['Behind The Scenes', 'Content Creation', 'Studio Work'],
      },
      {
        id: 'photo-sk-5',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
        caption: 'Summer Linen Wardrobe Lookbook',
        category: 'lifestyle',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'Malibu Coast, CA',
        cameraGear: 'Fuji GFX 100 II',
        tags: ['Summer Style', 'Linen Lookbook', 'Beach Aesthetic'],
      },
      {
        id: 'photo-sk-6',
        url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=85',
        caption: 'Editorial Glamour Headshot • Glow & Tone',
        category: 'headshot',
        aspectRatio: 'square',
        date: 'November 2025',
        location: 'Beverly Hills Studio',
        cameraGear: 'Hasselblad X2D 100C',
        tags: ['Editorial', 'Portrait Photography', 'Beauty Closeup'],
      },
    ],
    aestheticVibe: 'Clean Minimalist • Warm Sun-Drenched Natural Glow',
    audience: {
      topCountries: [
        { country: 'United States', percentage: 46 },
        { country: 'Germany & DACH', percentage: 22 },
        { country: 'United Kingdom', percentage: 18 },
        { country: 'France', percentage: 14 },
      ],
      genderSplit: { female: 78, male: 22 },
      topAgeGroup: '22–34 Years (64%)',
    },
    reviews: [
      {
        id: 'rev-1',
        brandName: 'Sephora Paris',
        brandLogo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'Sophie delivered extraordinary work! Her Reel generated over 300k views in 48 hours and drove a remarkable 4.2x ROAS for our launch.',
        campaignName: 'Hydration Serum Drop',
        date: 'February 2026',
      },
      {
        id: 'rev-2',
        brandName: 'Dior Beauty',
        brandLogo: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'Punctual, professional, and clear communication. The raw UGC content was shot impeccably and converted way above our historical paid social baseline.',
        campaignName: 'Organic Cleanser UGC',
        date: 'January 2026',
      },
      {
        id: 'rev-3',
        brandName: 'Glossier',
        brandLogo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'One of the smoothest creator collaborations we have run. The aesthetic was completely aligned with our moodboard and drove 14k link clicks.',
        campaignName: 'Cloud Paint Spring Drop',
        date: 'December 2025',
      },
      {
        id: 'rev-4',
        brandName: 'Charlotte Tilbury',
        brandLogo: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'Flawless 4K color grading, natural product application, and timely delivery. Sophie is now on our priority creator roster.',
        campaignName: 'Pillow Talk Glow Campaign',
        date: 'November 2025',
      },
      {
        id: 'rev-5',
        brandName: 'CeraVe',
        brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'Authentic dermatologist routine integration with high comment engagement. Zero revisions required.',
        campaignName: 'Moisturizing Cream Routine',
        date: 'October 2025',
      },
      {
        id: 'rev-6',
        brandName: 'Rituals Cosmetics',
        brandLogo: 'https://images.unsplash.com/photo-1608248597359-2169b91eb9c8?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        comment: 'Great storytelling and high conversion on promo codes. We are already booking our next seasonal campaign with Sophie.',
        campaignName: 'Sakura Body Care Launch',
        date: 'September 2025',
      },
    ],
  },
  {
    id: 'creator-02',
    name: 'Liam Carter',
    handle: 'liamcarter',
    gender: 'male',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    bio: 'Professional outdoor cinematographer, mountaineer, and drone pilot. Capturing untamed wilderness stories across Europe and North America.',
    location: 'Munich & Innsbruck',
    city: 'Munich',
    country: 'Germany',
    contactEmail: 'collabs@liamcarter.com',
    contactPhone: '+49 89 2441 5560',
    languages: ['English', 'German'],
    collaborationPreferences: ['sponsored', 'reviews', 'ambassador', 'events'],
    verified: true,
    categories: ['Travel', 'Cinematic Vlog', 'Tech'],
    tags: ['Outdoor', 'Travel', 'Drone 4K', 'Adventure', 'Camera Gear'],
    platforms: {
      instagram: {
        followers: 980000,
        followersFormatted: '980K',
        handle: '@liam.outdoors',
        engagementRate: '5.8%',
        avgViews: '420K',
        url: 'https://instagram.com/liam.outdoors',
      },
      tiktok: {
        followers: 640000,
        followersFormatted: '640K',
        handle: '@liamcarter',
        engagementRate: '7.4%',
        avgViews: '750K',
        url: 'https://tiktok.com/@liamcarter',
      },
      youtube: {
        followers: 850000,
        followersFormatted: '850K',
        handle: 'Liam Carter Cinema',
        engagementRate: '9.2%',
        avgViews: '980K',
        url: 'https://youtube.com/@liamcartercinema',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'Drone & 4K Field Tests',
      },
    },
    rating: 4.96,
    reviewsCount: 38,
    totalCollaborations: 94,
    startingPriceEur: 550,
    packages: [
      {
        id: 'pkg-lc-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: '4K Drone Adventure Reel / TikTok',
        type: 'reel',
        description: '60s mountain landscape reel with high-production drone cinematography and organic product integration.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 4K Drone Cinematography Reel', 'Color Graded 4K Master', 'TikTok Cross-Posting', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-lc-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Alpine Collab Bundle',
        type: 'bundle',
        description: 'High-retention 4K mountain Reel + 3x field Stories with link stickers and TikTok Spark ad whitelisting.',
        priceEur: 1350,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Mountain Reel', '3x Interactive Story Sequence', 'TikTok Audio Sync & Tag', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-lc-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Alpine Expedition Takeover',
        type: 'integrated',
        description: '90s dedicated mid-roll integration within high-viewership alpine exploration documentary + Reel cross-post.',
        priceEur: 2600,
        deliveryDays: 10,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated 10-15m Video Integration', 'Permanent Description Link & Card', '4K Cinematic Drone B-Roll', '90-Day Paid Ad Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-lc-1',
        brandName: "Arc'teryx",
        brandLogo: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Alpine Expedition Series 4K Reel',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=800&q=80',
        views: '480K',
        likes: '39K',
        comments: '1,840',
        shares: '9,200',
        engagementRate: '9.1%',
        duration: '0:58',
        aspectRatio: '9:16',
        platform: 'instagram',
        deliverableType: '60s 4K Drone Reel & Sound Design',
        description: 'Breathtaking 4K mountain ridge expedition in Chamonix showcasing the Arc\'teryx Alpha SV GORE-TEX Pro shell jacket under freezing gale winds.',
        soundTrack: 'Cinematic Mountain Ambience & FPV Drone Audio',
        completedDate: 'February 2026',
        packagePriceEur: 850,
      },
      {
        id: 'port-lc-1b',
        brandName: 'Salomon Outdoor',
        brandLogo: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Glacier Ascent Cinematic Story Sequence',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        views: '310K',
        likes: '24K',
        comments: '980',
        shares: '4,500',
        engagementRate: '7.8%',
        duration: '0:30',
        aspectRatio: '9:16',
        platform: 'instagram',
        deliverableType: '3x Story Sequence with Link Sticker',
        description: 'Live field test of Salomon Quest 4 GORE-TEX mountaineering boots traversing crevasse fields in the Austrian Alps.',
        soundTrack: 'Deep Bass Drone • Outdoor Sound',
        completedDate: 'January 2026',
        packagePriceEur: 550,
      },
      {
        id: 'port-lc-2',
        brandName: 'Peak Design',
        brandLogo: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Travel Camera Backpack Review & Stress Test',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
        views: '340K',
        likes: '29K',
        comments: '1,420',
        shares: '8,100',
        engagementRate: '8.8%',
        duration: '0:38',
        aspectRatio: '9:16',
        platform: 'tiktok',
        deliverableType: '30s High-Energy Viral TikTok Hook',
        description: 'Fast-paced gear packing & water-repellency stress test of the Everyday Backpack 30L under heavy mountain rainfall.',
        soundTrack: 'Trending Electro Beat • Fast Cuts',
        completedDate: 'February 2026',
        packagePriceEur: 550,
      },
      {
        id: 'port-lc-2b',
        brandName: 'GoPro',
        brandLogo: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=200&q=80',
        campaignTitle: '1000m Cliff Drop POV Action Short',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80',
        views: '620K',
        likes: '58K',
        comments: '2,900',
        shares: '18,400',
        engagementRate: '10.4%',
        duration: '0:22',
        aspectRatio: '9:16',
        platform: 'tiktok',
        deliverableType: 'Dedicated TikTok Video with Pinned Bio Link',
        description: 'First-person cliff-jumping POV recorded on GoPro HERO12 Black with Horizon Lock stabilization.',
        soundTrack: 'Extreme Action Phonk • Viral Audio',
        completedDate: 'January 2026',
        packagePriceEur: 550,
      },
      {
        id: 'port-lc-3',
        brandName: 'Sony Alpha',
        brandLogo: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Chasing Northern Lights Norway (Full 4K Vlog)',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        views: '610K',
        likes: '54K',
        comments: '4,210',
        shares: '21,000',
        engagementRate: '11.4%',
        duration: '14:20',
        aspectRatio: '16:9',
        platform: 'youtube',
        deliverableType: '15-Min Cinematic Documentary Integration',
        description: 'Arctic circle expedition testing Sony A7S III low-light ISO capabilities under sub-zero auroras in Lofoten, Norway.',
        soundTrack: 'Hans Zimmer Inspired Cinematic Score',
        completedDate: 'February 2026',
        packagePriceEur: 1600,
      },
      {
        id: 'port-lc-3b',
        brandName: 'DJI Global',
        brandLogo: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Winter In The Dolomites Drone Odyssey',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
        views: '520K',
        likes: '46K',
        comments: '3,100',
        shares: '14,200',
        engagementRate: '9.8%',
        duration: '8:45',
        aspectRatio: '16:9',
        platform: 'youtube',
        deliverableType: 'Full Dedicated YouTube Cinematic Film',
        description: 'Epic FPV and MasterShots cinematography exploring Tre Cime di Lavaredo with DJI Mavic 3 Pro.',
        soundTrack: 'Ambient Orchestral Soundtrack',
        completedDate: 'January 2026',
        packagePriceEur: 1600,
      },
      {
        id: 'port-lc-4',
        brandName: 'Patagonia',
        brandLogo: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Sustainable Shell Jacket Field Test Ad Set',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
        views: '290K',
        likes: '24K',
        comments: '1,120',
        shares: '6,400',
        engagementRate: '8.4%',
        duration: '0:30',
        aspectRatio: '9:16',
        platform: 'ugc',
        deliverableType: '2x 9:16 Commercial Ads for Paid Social',
        description: 'Raw high-energy UGC ad variations showing heavy rain testing, recycled fabrics, and waterproof zipper durability in 4K.',
        completedDate: 'February 2026',
        packagePriceEur: 750,
      },
      {
        id: 'port-lc-4b',
        brandName: 'Black Diamond',
        brandLogo: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=200&q=80',
        campaignTitle: 'Ice Axe & Crampons Rugged Field Test UGC Pack',
        mediaType: 'video',
        mediaUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=800&q=80',
        views: '330K',
        likes: '28K',
        comments: '1,350',
        shares: '7,800',
        engagementRate: '8.9%',
        duration: '0:45',
        aspectRatio: '9:16',
        platform: 'ugc',
        deliverableType: '5x 4K Raw Outdoor B-Roll Video Clips',
        description: 'Vertical 4K video ad assets demonstrating ice climbing grip, steel teeth penetration, and lightweight ergonomic handling.',
        completedDate: 'December 2025',
        packagePriceEur: 950,
      },
    ],
    photos: [
      {
        id: 'photo-lc-1',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Commercial Creator Headshot • Clean Natural Portrait',
        category: 'headshot',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Munich Studio, Germany',
        cameraGear: 'Sony A1 • 85mm f/1.4 GM',
        tags: ['Headshot', 'Commercial Face', 'Male Creator'],
      },
      {
        id: 'photo-lc-2',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Alpine Summit Expedition • Dolomites, Italy',
        category: 'outdoors',
        aspectRatio: 'landscape',
        date: 'January 2026',
        location: 'Tre Cime di Lavaredo, Italy',
        cameraGear: 'Sony A7S III • 24-70mm GM II',
        tags: ['Mountaineering', 'Outdoor Gear', 'Extreme Weather'],
      },
      {
        id: 'photo-lc-3',
        url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=85',
        caption: 'Travel Lifestyle & Adventure Apparel Shoot',
        category: 'lifestyle',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Innsbruck, Austria',
        cameraGear: 'Leica SL2-S',
        tags: ['Streetwear', 'Apparel Modeling', 'Adventure Lifestyle'],
      },
      {
        id: 'photo-lc-4',
        url: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=1200&q=85',
        caption: 'Behind The Scenes • 4K Drone Operations in Chamonix',
        category: 'bts',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Chamonix-Mont-Blanc, France',
        cameraGear: 'DJI Inspire 3 & FPV',
        tags: ['BTS Cinematography', 'Drone Pilot', 'Production Setup'],
      },
      {
        id: 'photo-lc-5',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sub-Zero Field Test Portrait • Arctic Lofoten',
        category: 'headshot',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'Lofoten Islands, Norway',
        cameraGear: 'Sony A7R V • 50mm f/1.2 GM',
        tags: ['Cold Climate', 'Winter Headshot', 'Authentic Expression'],
      },
      {
        id: 'photo-lc-6',
        url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=85',
        caption: 'Campfire & Vanlife Expedition Shoot',
        category: 'lifestyle',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Bavarian Alps',
        cameraGear: 'Canon EOS R5C',
        tags: ['Vanlife', 'Campfire', 'Outdoor Camping'],
      },
    ],
    aestheticVibe: 'Cinematic Rugged • High-Altitude Mountaineering & Wild Landscapes',
    audience: {
      topCountries: [
        { country: 'Germany', percentage: 38 },
        { country: 'Austria & Switzerland', percentage: 24 },
        { country: 'United States', percentage: 20 },
        { country: 'UK', percentage: 18 },
      ],
      genderSplit: { female: 35, male: 65 },
      topAgeGroup: '25–40 Years (71%)',
    },
    reviews: [
      {
        id: 'rev-lc-1',
        brandName: 'Patagonia Europe',
        brandLogo: 'https://cdn.simpleicons.org/patagonia/0A0A0A',
        rating: 5,
        comment: 'Liam produced cinema-quality visuals that surpassed our expectations. One of our top performing creator partnerships this quarter.',
        campaignName: 'Winter Alpine Summit',
        date: 'February 2026',
      },
      {
        id: 'rev-lc-2',
        brandName: 'GoPro EMEA',
        brandLogo: 'https://cdn.simpleicons.org/gopro/0A0A0A',
        rating: 5,
        comment: 'High production quality and swift turnaround. The drone shots elevated our product to new heights.',
        campaignName: 'Outdoor Line Launch',
        date: 'January 2026',
      },
    ],
  },
  {
    id: 'creator-03',
    name: 'Maya Chen',
    handle: 'mayachen',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    bio: 'Certified strength trainer and holistic wellness advocate. Helping over 2M+ followers build sustainable habits and athletic performance.',
    location: 'London, UK',
    city: 'London',
    country: 'United Kingdom',
    contactEmail: 'collabs@mayachen.co.uk',
    contactPhone: '+44 20 7946 0912',
    languages: ['English', 'Mandarin'],
    collaborationPreferences: ['sponsored', 'ugc', 'ambassador', 'reviews'],
    verified: true,
    categories: ['Fitness', 'Health', 'Lifestyle'],
    tags: ['Fitness', 'Wellness', 'Nutrition', 'Athleisure', 'Mental Health'],
    platforms: {
      instagram: {
        followers: 1400000,
        followersFormatted: '1.4M',
        handle: '@maya.chen.fit',
        engagementRate: '5.1%',
        avgViews: '380K',
        url: 'https://instagram.com/maya.chen.fit',
      },
      tiktok: {
        followers: 920000,
        followersFormatted: '920K',
        handle: '@mayachen',
        engagementRate: '6.8%',
        avgViews: '620K',
        url: 'https://tiktok.com/@mayachen',
      },
      youtube: {
        followers: 410000,
        followersFormatted: '410K',
        handle: 'Maya Chen Fitness',
        engagementRate: '7.9%',
        avgViews: '180K',
        url: 'https://youtube.com/@mayachenfitness',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'High Energy UGC Hook',
      },
    },
    startingPriceEur: 750,
    rating: 5.0,
    reviewsCount: 56,
    totalCollaborations: 160,
    packages: [
      {
        id: 'pkg-mc-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Dedicated Fitness Reel / TikTok',
        type: 'reel',
        description: 'High-energy 60s workout breakdown demonstrating active apparel, training gear, or supplement benefits.',
        priceEur: 950,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 60s 4K Fitness Reel', 'TikTok Sound Sync & Audio Match', 'Bio Link & Tag', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-mc-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Workout Routine & Story Bundle',
        type: 'bundle',
        description: 'Full workout integration wearing/using your product with 3x Story follow-ups, swipe-up links, and Spark ad rights.',
        priceEur: 1650,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Feed Reel', '3x Story Sequence with Direct Link', 'TikTok Cross-Posting & Tag', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-mc-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram', 'tiktok'],
        title: '360° Athletic Campaign Takeover',
        type: 'video',
        description: 'Integrated 90-second mid-roll sponsor in a 20-minute guided home workout routine plus Reel cross-post and commercial rights.',
        priceEur: 3200,
        deliveryDays: 8,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['90s Dedicated Mid-Roll Video Feature', 'Branded Workout Graphics Overlay', '1x 4K Reel + 3x Stories', '90-Day Full Commercial Whitelisting'],
      },
    ],
    portfolio: [
      {
        id: 'port-mc-1',
        brandName: 'Gymshark',
        campaignTitle: 'Seamless Energy Drop',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
        views: '580K',
        likes: '48K',
        comments: '1,240',
        engagementRate: '9.1%',
        platform: 'instagram',
        deliverableType: 'Instagram Reel & Carousel',
        description: 'High-energy studio showcase for the Gymshark Seamless Energy collection with workout form demos, sizing breakdowns, and direct bio-link referral.',
      },
      {
        id: 'port-mc-2',
        brandName: 'Alo Yoga',
        campaignTitle: 'Morning Stretch & Mindfulness',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
        views: '430K',
        likes: '37K',
        comments: '890',
        engagementRate: '8.8%',
        platform: 'tiktok',
        deliverableType: 'TikTok Morning Flow',
        description: 'Aesthetic sunrise yoga & breathwork flow featuring Alo Yoga seamless activewear, focusing on calm morning routines, mindful stretching, and clean wellness aesthetics.',
      },
      {
        id: 'port-mc-3',
        brandName: 'AG1 Athletic Greens',
        campaignTitle: 'Daily Nutrition Routine Guide',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=600&q=80',
        views: '620K',
        likes: '51K',
        comments: '1,450',
        engagementRate: '8.5%',
        platform: 'youtube',
        deliverableType: 'YouTube Short & Integration',
        description: 'Complete daily nutritional protocol breakdown showcasing AG1 morning preparation, highlighting taste profile and energy consistency for high-performance lifestyle.',
      },
      {
        id: 'port-mc-4',
        brandName: 'Optimum Nutrition',
        brandLogo: 'https://cdn.simpleicons.org/optimumnutrition/0A0A0A',
        campaignTitle: 'Clean Nutrition Shake Routine - 520K Views',
        mediaType: 'video',
        mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-warm-up-exercises-at-the-gym-40290-large.mp4',
        views: '520K',
        likes: '49K',
        comments: '980',
        engagementRate: '9.6%',
        platform: 'tiktok',
        deliverableType: 'TikTok Video',
        description: 'Demonstrated post-workout shake preparation resulting in an estimated 1,800 promo code redemptions.',
      },
    ],
    photos: [
      {
        id: 'photo-mc-1',
        url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Studio portrait shoot for fitness apparel campaign',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'London Studio, UK',
        cameraGear: 'Sony A7R V + 85mm f/1.4 GM',
        tags: ['Fitness', 'Studio', 'Portrait'],
      },
      {
        id: 'photo-mc-2',
        url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
        caption: 'Olympic lifting strength session',
        category: 'action',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Equinox London',
        cameraGear: 'Canon EOS R5 + 24-70mm f/2.8',
        tags: ['Training', 'Athletic'],
      },
      {
        id: 'photo-mc-3',
        url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
        caption: 'Post-workout recovery & athletic lifestyle',
        category: 'lifestyle',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Hyde Park, London',
        cameraGear: 'Sony A7R V + 35mm f/1.4 GM',
        tags: ['Athleisure', 'Recovery', 'Lifestyle'],
      },
      {
        id: 'photo-mc-4',
        url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
        caption: 'Holistic meal prep & clean nutrition',
        category: 'editorial',
        aspectRatio: 'landscape',
        date: 'December 2025',
        location: 'London Kitchen Studio',
        cameraGear: 'Canon EOS R5 + 50mm f/1.2',
        tags: ['Nutrition', 'Meal Prep', 'Clean Eating'],
      },
    ],
    aestheticVibe: 'High-Energy Athletic • Clean Studio Performance & Holistic Wellness',
    audience: {
      topCountries: [
        { country: 'United Kingdom', percentage: 42 },
        { country: 'United States', percentage: 28 },
        { country: 'Germany', percentage: 16 },
        { country: 'Australia', percentage: 14 },
      ],
      genderSplit: { female: 68, male: 32 },
      topAgeGroup: '20–35 Years (76%)',
    },
    reviews: [
      {
        id: 'rev-mc-1',
        brandName: 'Gymshark UK',
        brandLogo: 'https://cdn.simpleicons.org/gymshark/0A0A0A',
        rating: 5,
        comment: 'Maya is a force of nature. Flawless execution, insane engagement from her community, and great ROI.',
        campaignName: 'Seamless Collection Launch',
        date: 'January 2026',
      },
      {
        id: 'rev-mc-2',
        brandName: 'Nike Training',
        brandLogo: 'https://cdn.simpleicons.org/nike/0A0A0A',
        rating: 5,
        comment: 'Incredible authenticity and professionalism. The content converted exceptionally well on our organic and paid funnels.',
        campaignName: 'Summer Athleisure Drop',
        date: 'December 2025',
      },
      {
        id: 'rev-mc-3',
        brandName: 'Lululemon',
        brandLogo: 'https://cdn.simpleicons.org/lululemon/0A0A0A',
        rating: 5,
        comment: 'Super fast communication and top-tier photography quality. Maya brought genuine athletic credibility to the campaign.',
        campaignName: 'Align Pant Creator Campaign',
        date: 'November 2025',
      },
      {
        id: 'rev-mc-4',
        brandName: 'Olaplex Fitness',
        brandLogo: 'https://cdn.simpleicons.org/olaplex/0A0A0A',
        rating: 5,
        comment: 'Very engaging post-workout hair routine. Drove thousands of link taps and great brand sentiment.',
        campaignName: 'Post-Workout Haircare Routine',
        date: 'October 2025',
      },
    ],
  },
  {
    id: 'creator-04',
    name: 'Noah Becker',
    handle: 'noahbecker',
    gender: 'male',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    bio: 'Contemporary menswear stylist and creative director. Curating clean minimalist aesthetics and capsule wardrobes.',
    location: 'Berlin, Germany',
    city: 'Berlin',
    country: 'Germany',
    contactEmail: 'collabs@noahbecker.de',
    contactPhone: '+49 30 5553 8812',
    languages: ['English', 'German'],
    collaborationPreferences: ['sponsored', 'ugc', 'events', 'ambassador'],
    verified: true,
    categories: ['Fashion', 'Lifestyle', "Men's Style"],
    tags: ['Fashion', 'Streetwear', 'Tailoring', 'Minimalism', 'Grooming'],
    platforms: {
      instagram: {
        followers: 520000,
        followersFormatted: '520K',
        handle: '@noah.becker',
        engagementRate: '4.6%',
        avgViews: '140K',
        url: 'https://instagram.com/noah.becker',
      },
      tiktok: {
        followers: 310000,
        followersFormatted: '310K',
        handle: '@noahbeckerstyle',
        engagementRate: '5.9%',
        avgViews: '210K',
        url: 'https://tiktok.com/@noahbeckerstyle',
      },
      youtube: {
        followers: 180000,
        followersFormatted: '180K',
        handle: 'Noah Becker Style',
        engagementRate: '6.5%',
        avgViews: '80K',
        url: 'https://youtube.com/@noahbeckerstyle',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'Studio Aesthetic',
      },
    },
    startingPriceEur: 450,
    rating: 4.94,
    reviewsCount: 29,
    totalCollaborations: 72,
    packages: [
      {
        id: 'pkg-nb-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Minimalist Lookbook Reel / TikTok',
        type: 'reel',
        description: '45s outfit transition reel with modern jazz/lo-fi audio sync showing multiple styling angles in Berlin locations.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 45s 4K Reel', 'Color Graded 4K Master', 'TikTok Cross-Posting & Audio Sync', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-nb-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Capsule Wardrobe Bundle',
        type: 'bundle',
        description: 'High-converting 4K Reel + 3x interactive Story frames with direct swipe-up links and Spark ad whitelisting.',
        priceEur: 1350,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Fashion Reel', '3x Story Sequence with Link Stickers', 'TikTok Styling Video', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-nb-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Fashion Week Brand Takeover',
        type: 'video',
        description: 'Dedicated 60-90s sponsor segment in full seasonal wardrobe essentials guide + Reel cross-post and commercial rights.',
        priceEur: 2800,
        deliveryDays: 8,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated Seasonal Lookbook Integration', 'Top Pinned Comment & Description Link', '1x 4K Reel + 3x Stories', '90-Day Paid Media Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-nb-1',
        brandName: 'COS',
        campaignTitle: 'Autumn Minimalist Knitwear',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
        views: '320K',
        likes: '28K',
        platform: 'instagram',
      },
      {
        id: 'port-nb-2',
        brandName: 'Acne Studios',
        campaignTitle: 'Denim Fit Guide 2026',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80',
        views: '280K',
        likes: '24K',
        platform: 'tiktok',
      },
      {
        id: 'port-nb-3',
        brandName: 'Arket',
        campaignTitle: 'Essentials Wardrobe Integration',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=600&q=80',
        views: '190K',
        likes: '16K',
        platform: 'youtube',
      },
      {
        id: 'port-nb-4',
        brandName: 'Samsøe Samsøe',
        campaignTitle: 'Winter Outerwear Lookbook UGC',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
        views: '240K',
        likes: '19K',
        platform: 'ugc',
      },
    ],
    photos: [
      {
        id: 'photo-nb-1',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Minimalist menswear styling portrait in Berlin',
        category: 'editorial',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Mitte, Berlin',
        cameraGear: 'Leica Q3 • 28mm f/1.7',
        tags: ['Menswear', 'Tailoring', 'Minimalism'],
      },
      {
        id: 'photo-nb-2',
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Autumn wardrobe capsule & texture study',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'January 2026',
        location: 'Studio Berlin',
        cameraGear: 'Hasselblad X2D 100C',
        tags: ['Capsule Wardrobe', 'Studio', 'Fashion'],
      },
      {
        id: 'photo-nb-3',
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
        caption: 'Street style lookbook in Kreuzberg',
        category: 'lifestyle',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'Kreuzberg, Berlin',
        cameraGear: 'Sony A7R V + 50mm f/1.2 GM',
        tags: ['Streetwear', 'Urban', 'Lifestyle'],
      },
      {
        id: 'photo-nb-4',
        url: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=1200&q=80',
        caption: 'Creative direction & architectural styling',
        category: 'editorial',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Museum Island, Berlin',
        cameraGear: 'Leica SL2-S + 35mm APO',
        tags: ['Architecture', 'Creative Direction'],
      },
    ],
    audience: {
      topCountries: [
        { country: 'Germany', percentage: 52 },
        { country: 'France', percentage: 18 },
        { country: 'Netherlands', percentage: 15 },
        { country: 'UK', percentage: 15 },
      ],
      genderSplit: { female: 28, male: 72 },
      topAgeGroup: '22–38 Years (69%)',
    },
    reviews: [
      {
        id: 'rev-nb-1',
        brandName: 'Zara Berlin',
        brandLogo: 'https://cdn.simpleicons.org/zara/0A0A0A',
        rating: 5,
        comment: 'Noah possesses exceptional artistic direction. His photos matched our global lookbook aesthetic completely.',
        campaignName: 'Trans-Seasonal Knitwear',
        date: 'February 2026',
      },
      {
        id: 'rev-nb-2',
        brandName: 'Gucci Europe',
        brandLogo: 'https://cdn.simpleicons.org/gucci/0A0A0A',
        rating: 5,
        comment: 'Sophisticated aesthetic and immaculate delivery on time. Our audience loved his styling advice.',
        campaignName: 'Denim Capsule',
        date: 'January 2026',
      },
    ],
  },
  {
    id: 'creator-05',
    name: 'Emma Rossi',
    handle: 'emmarossi',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Pastry chef and culinary creator crafting approachable gourmet recipes, kitchen equipment tests, and dining guides.',
    location: 'Milan & Zurich',
    city: 'Milan',
    country: 'Italy',
    contactEmail: 'contact@emmarossi.it',
    contactPhone: '+39 02 8739 1234',
    languages: ['Italian', 'English'],
    collaborationPreferences: ['sponsored', 'reviews', 'ugc', 'ambassador'],
    verified: true,
    categories: ['Food', 'Cuisine', 'Lifestyle'],
    tags: ['Food', 'Recipes', 'Baking', 'Kitchen Appliances', 'Wine'],
    platforms: {
      instagram: {
        followers: 850000,
        followersFormatted: '850K',
        handle: '@emmarossi.table',
        engagementRate: '5.8%',
        avgViews: '290K',
        url: 'https://instagram.com/emmarossi.table',
      },
      tiktok: {
        followers: 390000,
        followersFormatted: '390K',
        handle: '@emmarossicooks',
        engagementRate: '6.4%',
        avgViews: '380K',
        url: 'https://tiktok.com/@emmarossicooks',
      },
      youtube: {
        followers: 120000,
        followersFormatted: '120K',
        handle: 'Emma Rossi Kitchen',
        engagementRate: '8.1%',
        avgViews: '70K',
        url: 'https://youtube.com/@emmarossikitchen',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: '4K Tabletop Macro Lighting',
      },
    },
    startingPriceEur: 550,
    rating: 4.97,
    reviewsCount: 33,
    totalCollaborations: 85,
    packages: [
      {
        id: 'pkg-er-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Gourmet Recipe Reel / TikTok',
        type: 'reel',
        description: 'Sensory 60s recipe video featuring your ingredient or kitchen tool with full recipe text in caption.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 60s 4K Macro Recipe Reel', 'TikTok Sound Mix & Audio Match', 'Ingredient Tag & Bio Link', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-er-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Culinary Collab Bundle',
        type: 'bundle',
        description: 'High-retention 4K Recipe Reel + 3x step-by-step cooking Stories with link stickers and Spark ad rights.',
        priceEur: 1350,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Recipe Reel', '3x Cooking Stories with Purchase Links', 'TikTok Cross-Posting & Audio Sync', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-er-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Culinary Masterclass Takeover',
        type: 'video',
        description: 'Full 10-15 minute cooking masterclass built entirely around testing and elevating your brand appliance + Reel cross-post.',
        priceEur: 2600,
        deliveryDays: 10,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated 12m Masterclass Video', 'Permanent Ingredient Link & Card', '1x 4K Reel + 3x Stories', '90-Day Paid Media Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-er-1',
        brandName: 'Breville',
        campaignTitle: 'Barista Touch Espresso Masterclass',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
        views: '410K',
        likes: '35K',
        platform: 'instagram',
      },
      {
        id: 'port-er-2',
        brandName: 'Le Creuset',
        campaignTitle: 'Dutch Oven Sourdough ASMR',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        views: '520K',
        likes: '48K',
        platform: 'tiktok',
      },
      {
        id: 'port-er-3',
        brandName: 'Nespresso',
        campaignTitle: 'Summer Iced Coffee Recipes',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
        views: '230K',
        likes: '19K',
        platform: 'youtube',
      },
      {
        id: 'port-er-4',
        brandName: 'Zwilling',
        campaignTitle: 'Damascus Knife Skills UGC',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
        views: '310K',
        likes: '29K',
        platform: 'ugc',
      },
    ],
    photos: [
      {
        id: 'photo-er-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
        caption: 'Culinary portrait & pastry studio kitchen',
        category: 'editorial',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Milan, Italy',
        cameraGear: 'Sony A7R V + 85mm f/1.4 GM',
        tags: ['Chef', 'Pastry', 'Portrait'],
      },
      {
        id: 'photo-er-2',
        url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
        caption: 'Artisan sourdough baking in Dutch Oven',
        category: 'action',
        aspectRatio: 'landscape',
        date: 'January 2026',
        location: 'Milan Studio',
        cameraGear: 'Canon EOS R5 + 24-70mm f/2.8',
        tags: ['Baking', 'Culinary', 'Food Photography'],
      },
      {
        id: 'photo-er-3',
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80',
        caption: 'Specialty espresso extraction & latte art',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'Zurich, Switzerland',
        cameraGear: 'Sony A7R V + 50mm f/1.2',
        tags: ['Coffee', 'Barista', 'Aesthetics'],
      },
      {
        id: 'photo-er-4',
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mediterranean seasonal table setting',
        category: 'lifestyle',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Lake Como, Italy',
        cameraGear: 'Leica Q3 • 28mm f/1.7',
        tags: ['Table Setting', 'Lifestyle', 'Dining'],
      },
    ],
    audience: {
      topCountries: [
        { country: 'Italy', percentage: 40 },
        { country: 'Germany & Switzerland', percentage: 32 },
        { country: 'France', percentage: 28 },
      ],
      genderSplit: { female: 72, male: 28 },
      topAgeGroup: '24–45 Years (68%)',
    },
    reviews: [
      {
        id: 'rev-er-1',
        brandName: 'Starbucks Reserve',
        brandLogo: 'https://cdn.simpleicons.org/starbucks/0A0A0A',
        rating: 5,
        comment: 'Emma created mouthwatering content for our espresso machine campaign. The video drove our highest conversion spike this month.',
        campaignName: 'Barista Touch Launch',
        date: 'January 2026',
      },
      {
        id: 'rev-er-2',
        brandName: 'Nespresso Global',
        brandLogo: 'https://cdn.simpleicons.org/nespresso/0A0A0A',
        rating: 5,
        comment: 'Brilliant aesthetic and delicious recipes. Our coffee pods sold out within 48 hours of her post!',
        campaignName: 'Summer Iced Coffee',
        date: 'December 2025',
      },
    ],
  },
  {
    id: 'creator-06',
    name: 'Daniel Park',
    handle: 'danielpark',
    gender: 'male',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Software engineer and desk setup enthusiast reviewing developer tools, productivity gadgets, and AI hardware.',
    location: 'San Francisco, CA',
    city: 'San Francisco',
    country: 'United States',
    contactEmail: 'partners@danielpark.io',
    contactPhone: '+1 (415) 890-3412',
    languages: ['English', 'Korean'],
    collaborationPreferences: ['sponsored', 'reviews', 'ugc', 'affiliate'],
    verified: true,
    categories: ['Tech', 'Gaming', 'Business'],
    tags: ['Tech', 'Gadgets', 'Productivity', 'Desk Setup', 'AI Tools'],
    platforms: {
      instagram: {
        followers: 620000,
        followersFormatted: '620K',
        handle: '@danielpark.tech',
        engagementRate: '4.2%',
        avgViews: '190K',
        url: 'https://instagram.com/danielpark.tech',
      },
      tiktok: {
        followers: 790000,
        followersFormatted: '790K',
        handle: '@danielparktech',
        engagementRate: '7.8%',
        avgViews: '550K',
        url: 'https://tiktok.com/@danielparktech',
      },
      youtube: {
        followers: 340000,
        followersFormatted: '340K',
        handle: 'Daniel Park Tech',
        engagementRate: '8.6%',
        avgViews: '140K',
        url: 'https://youtube.com/@danielparktech',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'Software & SaaS Demos',
      },
    },
    startingPriceEur: 600,
    rating: 4.99,
    reviewsCount: 47,
    totalCollaborations: 110,
    packages: [
      {
        id: 'pkg-dp-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Productivity Workflow Reel / TikTok',
        type: 'reel',
        description: 'Fast-paced 60s desk setup video showing your tech accessory or software seamlessly integrated into daily developer workflows.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 60s 4K Workspace Reel', 'TikTok Sound Sync & Audio Match', 'Bio Link & Tag', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-dp-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Workspace Showcase Bundle',
        type: 'bundle',
        description: 'High-converting 4K desk setup Reel + 3x interactive Stories with direct links and Spark ad authorization.',
        priceEur: 1350,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Desk Reel', '3x Story Sequence with Link Stickers', 'TikTok Cross-Posting & Audio Sync', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-dp-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Tech & Desk Tour Takeover',
        type: 'video',
        description: '90s dedicated sponsor segment in a highly anticipated quarterly desk setup update video + Reel cross-post and commercial rights.',
        priceEur: 2700,
        deliveryDays: 10,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated 90s Desk Tour Segment', 'Permanent Top Description Link & Card', '1x 4K Reel + 3x Stories', '90-Day Paid Media Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-dp-1',
        brandName: 'Keychron',
        campaignTitle: 'Q1 Pro Custom Mechanical Keyboard',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
        views: '460K',
        likes: '41K',
        platform: 'instagram',
      },
      {
        id: 'port-dp-2',
        brandName: 'Logitech G',
        campaignTitle: 'Ergo Lift Vertical Mouse Review',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
        views: '620K',
        likes: '58K',
        platform: 'tiktok',
      },
      {
        id: 'port-dp-3',
        brandName: 'Dell Technologies',
        campaignTitle: 'UltraSharp 40 Curved Monitor Review',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
        views: '310K',
        likes: '26K',
        platform: 'youtube',
      },
      {
        id: 'port-dp-4',
        brandName: 'Razer',
        campaignTitle: 'Blade 16 Gaming Laptop Performance Test',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
        views: '290K',
        likes: '25K',
        platform: 'ugc',
      },
    ],
    photos: [
      {
        id: 'photo-dp-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Minimalist tech workspace & engineering setup portrait',
        category: 'editorial',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'San Francisco, CA',
        cameraGear: 'Sony A7R V + 50mm f/1.2 GM',
        tags: ['Engineer', 'Developer', 'Workspace'],
      },
      {
        id: 'photo-dp-2',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
        caption: 'Ultrawide monitor & ambient desk aesthetic',
        category: 'studio',
        aspectRatio: 'landscape',
        date: 'January 2026',
        location: 'Studio SF',
        cameraGear: 'Canon EOS R5 + 24-70mm f/2.8',
        tags: ['Desk Setup', 'Tech', 'Hardware'],
      },
      {
        id: 'photo-dp-3',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80',
        caption: 'Custom mechanical keyboard & ergonomic gear review',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'San Francisco, CA',
        cameraGear: 'Sony A7R V + 90mm Macro',
        tags: ['Keyboards', 'Peripherals', 'Productivity'],
      },
      {
        id: 'photo-dp-4',
        url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
        caption: 'AI hardware & workstation benchmark testing',
        category: 'editorial',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Silicon Valley Studio',
        cameraGear: 'Leica Q3 • 28mm f/1.7',
        tags: ['AI Hardware', 'Benchmark', 'Tech Review'],
      },
    ],
    audience: {
      topCountries: [
        { country: 'United States', percentage: 54 },
        { country: 'Germany', percentage: 18 },
        { country: 'Canada', percentage: 15 },
        { country: 'UK', percentage: 13 },
      ],
      genderSplit: { female: 18, male: 82 },
      topAgeGroup: '18–35 Years (81%)',
    },
    reviews: [
      {
        id: 'rev-dp-1',
        brandName: 'Razer EMEA',
        brandLogo: 'https://cdn.simpleicons.org/razer/0A0A0A',
        rating: 5,
        comment: 'Daniel is the benchmark of tech creators. Clear audio, stunning lighting, and true technical competence.',
        campaignName: 'Q1 Pro Launch',
        date: 'January 2026',
      },
      {
        id: 'rev-dp-2',
        brandName: 'Logitech G',
        brandLogo: 'https://cdn.simpleicons.org/logitech/0A0A0A',
        rating: 5,
        comment: 'His desk setup integration converted extremely well among software engineers. Outstanding partnership!',
        campaignName: 'Ergo Series Campaign',
        date: 'December 2025',
      },
    ],
  },
  {
    id: 'creator-07',
    name: 'Isabella Torres',
    handle: 'isabellatorres',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Sun-drenched Mediterranean lifestyle, boutique resort showcases, and sustainable summer fashion.',
    location: 'Barcelona, Spain',
    city: 'Barcelona',
    country: 'Spain',
    contactEmail: 'collabs@isabellatorres.es',
    contactPhone: '+34 93 412 8790',
    languages: ['Spanish', 'English'],
    collaborationPreferences: ['sponsored', 'ugc', 'ambassador', 'events'],
    verified: true,
    categories: ['Travel', 'Lifestyle', 'Fashion'],
    tags: ['Travel', 'Resorts', 'Bikinis', 'Summer Style', 'Hotel Reviews'],
    platforms: {
      instagram: {
        followers: 670000,
        followersFormatted: '670K',
        handle: '@isabella.torres',
        engagementRate: '5.2%',
        avgViews: '220K',
        url: 'https://instagram.com/isabella.torres',
      },
      tiktok: {
        followers: 480000,
        followersFormatted: '480K',
        handle: '@isabellatorres',
        engagementRate: '6.0%',
        avgViews: '310K',
        url: 'https://tiktok.com/@isabellatorres',
      },
      youtube: {
        followers: 210000,
        followersFormatted: '210K',
        handle: 'Isabella Summer Diaries',
        engagementRate: '7.4%',
        avgViews: '90K',
        url: 'https://youtube.com/@isabellasummerdiaries',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'Mediterranean Sunlit Aesthetics',
      },
    },
    startingPriceEur: 500,
    rating: 4.95,
    reviewsCount: 31,
    totalCollaborations: 78,
    packages: [
      {
        id: 'pkg-it-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Sunset Villa & Resort Reel / TikTok',
        type: 'reel',
        description: 'Aesthetic 60s reel showcasing resort amenities, beachwear, or dining in warm Mediterranean golden hour light.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 60s 4K Golden Hour Reel', 'TikTok Sound Sync & Audio Match', 'Location Tag & Bio Link', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-it-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Mediterranean Collab Bundle',
        type: 'bundle',
        description: 'High-converting 4K resort Reel + 3x lifestyle Stories with direct booking/purchase links and Spark ad rights.',
        priceEur: 1350,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Resort Reel', '3x Story Sequence with Link Stickers', 'TikTok Cross-Posting & Tag', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-it-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Luxury Travel & Resort Takeover',
        type: 'video',
        description: 'Dedicated 90s feature in travel vlog highlighting luxury accommodation and island excursions + Reel cross-post.',
        priceEur: 2800,
        deliveryDays: 10,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated 90s Travel Segment', 'Permanent Top Description Link & Card', '1x 4K Reel + 3x Stories', '90-Day Paid Media Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-it-1',
        brandName: 'W Hotels',
        campaignTitle: 'W Barcelona Summer Terrace',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
        views: '540K',
        likes: '46K',
        platform: 'instagram',
      },
      {
        id: 'port-it-2',
        brandName: 'Mango',
        campaignTitle: 'Mediterranean Linen Capsule',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
        views: '390K',
        likes: '31K',
        platform: 'tiktok',
      },
      {
        id: 'port-it-3',
        brandName: 'Nobu Hotels',
        campaignTitle: 'Ibiza Weekend Escape',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
        views: '240K',
        likes: '19K',
        platform: 'youtube',
      },
      {
        id: 'port-it-4',
        brandName: 'Rituals Cosmetics',
        campaignTitle: 'Karma Sun Care Line UGC',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80',
        views: '260K',
        likes: '21K',
        platform: 'ugc',
      },
    ],
    photos: [
      {
        id: 'photo-it-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mediterranean golden hour portrait & resort aesthetic',
        category: 'editorial',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Barcelona, Spain',
        cameraGear: 'Sony A7R V + 85mm f/1.4 GM',
        tags: ['Mediterranean', 'Golden Hour', 'Resort'],
      },
      {
        id: 'photo-it-2',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Sun-drenched coastal excursion & beachwear styling',
        category: 'lifestyle',
        aspectRatio: 'landscape',
        date: 'January 2026',
        location: 'Costa Brava, Spain',
        cameraGear: 'Canon EOS R5 + 24-70mm f/2.8',
        tags: ['Beachwear', 'Coastal', 'Summer'],
      },
      {
        id: 'photo-it-3',
        url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
        caption: 'Luxury rooftop pool & sunset lounge campaign',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'W Barcelona',
        cameraGear: 'Leica Q3 • 28mm f/1.7',
        tags: ['Luxury Hotel', 'Rooftop', 'Sunset'],
      },
      {
        id: 'photo-it-4',
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mediterranean linen capsule & terrace morning',
        category: 'lifestyle',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Ibiza, Spain',
        cameraGear: 'Sony A7R V + 35mm f/1.4 GM',
        tags: ['Linen Fashion', 'Terrace', 'Travel'],
      },
    ],
    audience: {
      topCountries: [
        { country: 'Spain', percentage: 36 },
        { country: 'Germany & DACH', percentage: 28 },
        { country: 'UK', percentage: 20 },
        { country: 'France', percentage: 16 },
      ],
      genderSplit: { female: 74, male: 26 },
      topAgeGroup: '20–32 Years (75%)',
    },
    reviews: [
      {
        id: 'rev-it-1',
        brandName: 'Marriott Luxury',
        brandLogo: 'https://cdn.simpleicons.org/marriott/0A0A0A',
        rating: 5,
        comment: 'Isabella has incredible visual taste. The lighting, tone, and organic vibe fit our brand DNA seamlessly.',
        campaignName: 'Summer Terrace Series',
        date: 'February 2026',
      },
      {
        id: 'rev-it-2',
        brandName: 'Airbnb Experiences',
        brandLogo: 'https://cdn.simpleicons.org/airbnb/0A0A0A',
        rating: 5,
        comment: 'Flawless styling and on-point aesthetic. Her audience engaged deeply with the collection.',
        campaignName: 'Linen Drop',
        date: 'December 2025',
      },
    ],
  },
  {
    id: 'creator-08',
    name: 'Chloe Nguyen',
    handle: 'chloenguyen',
    gender: 'female',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
    bio: 'Visual artist and interior designer transforming everyday spaces through thoughtful ceramics, paintings, and studio vlogs.',
    location: 'Amsterdam, Netherlands',
    city: 'Amsterdam',
    country: 'Netherlands',
    contactEmail: 'studio@chloenguyen.nl',
    contactPhone: '+31 20 794 5612',
    languages: ['Dutch', 'English'],
    collaborationPreferences: ['sponsored', 'ugc', 'reviews', 'affiliate'],
    verified: true,
    categories: ['Art', 'Creativity', 'Lifestyle'],
    tags: ['Art', 'Ceramics', 'Design', 'Studio Life', 'Interior'],
    platforms: {
      instagram: {
        followers: 420000,
        followersFormatted: '420K',
        handle: '@chloe.nguyen.art',
        engagementRate: '6.7%',
        avgViews: '180K',
        url: 'https://instagram.com/chloe.nguyen.art',
      },
      tiktok: {
        followers: 310000,
        followersFormatted: '310K',
        handle: '@chloeartstudio',
        engagementRate: '8.2%',
        avgViews: '290K',
        url: 'https://tiktok.com/@chloeartstudio',
      },
      youtube: {
        followers: 150000,
        followersFormatted: '150K',
        handle: 'Chloe Nguyen Studio',
        engagementRate: '9.0%',
        avgViews: '85K',
        url: 'https://youtube.com/@chloenguyenstudio',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: 'Cozy Aesthetic Lighting',
      },
    },
    startingPriceEur: 400,
    rating: 4.98,
    reviewsCount: 26,
    totalCollaborations: 64,
    packages: [
      {
        id: 'pkg-cn-1',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Studio Aesthetic Reel / TikTok',
        type: 'reel',
        description: 'Meditative 60s ceramics and studio process video subtly featuring your home decor, stationery, or design product.',
        priceEur: 650,
        deliveryDays: 4,
        revisions: 1,
        usageRights: '30-Day Organic Rights',
        inclusions: ['1x 60s 4K Studio Reel', 'Lo-Fi Chill Audio Mix', 'Tag in Image & Bio Link', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-cn-2',
        platform: 'instagram',
        platforms: ['instagram', 'tiktok'],
        title: 'Signature Ceramic & Interior Bundle',
        type: 'bundle',
        description: 'High-converting 4K process Reel + 3x styled interior Stories with link stickers and Spark ad whitelisting.',
        priceEur: 1150,
        deliveryDays: 5,
        revisions: 2,
        popular: true,
        usageRights: '60-Day Commercial Whitelisting',
        inclusions: ['1x Dedicated 4K Studio Reel', '3x Interactive Story Sequence', 'TikTok Cross-Posting & Audio Sync', '60-Day Spark Whitelisting Code'],
      },
      {
        id: 'pkg-cn-3',
        platform: 'youtube',
        platforms: ['youtube', 'instagram'],
        title: '360° Creative Studio Brand Takeover',
        type: 'video',
        description: 'Dedicated 60-90s sponsor segment in popular studio renovation and interior makeover vlog + Reel cross-post.',
        priceEur: 2400,
        deliveryDays: 10,
        revisions: 2,
        usageRights: '90-Day Full Commercial Rights',
        inclusions: ['Full Dedicated 90s Studio Tour Segment', 'Permanent Top Description Link & Card', '1x 4K Reel + 3x Stories', '90-Day Paid Media Rights'],
      },
    ],
    portfolio: [
      {
        id: 'port-cn-1',
        brandName: 'HAY',
        campaignTitle: 'Colour Crate Studio Organisation',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
        views: '280K',
        likes: '26K',
        platform: 'instagram',
      },
      {
        id: 'port-cn-2',
        brandName: 'Ferm Living',
        campaignTitle: 'Ceramic Tableware Showcase',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=600&q=80',
        views: '340K',
        likes: '31K',
        platform: 'tiktok',
      },
      {
        id: 'port-cn-3',
        brandName: 'Winsor & Newton',
        campaignTitle: 'Professional Gouache Field Test',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
        views: '160K',
        likes: '14K',
        platform: 'youtube',
      },
      {
        id: 'port-cn-4',
        brandName: 'Aesop',
        campaignTitle: 'Studio Hand Balm & Aromatics',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
        views: '210K',
        likes: '18K',
        platform: 'ugc',
      },
    ],
    photos: [
      {
        id: 'photo-cn-1',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
        caption: 'Studio portrait & ceramic sculpture in natural window light',
        category: 'editorial',
        aspectRatio: 'portrait',
        date: 'February 2026',
        location: 'Amsterdam, Netherlands',
        cameraGear: 'Sony A7R V + 50mm f/1.2 GM',
        tags: ['Ceramics', 'Artist', 'Studio Portrait'],
      },
      {
        id: 'photo-cn-2',
        url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
        caption: 'Handcrafted stoneware throwing on pottery wheel',
        category: 'action',
        aspectRatio: 'landscape',
        date: 'January 2026',
        location: 'Jordaan Studio, Amsterdam',
        cameraGear: 'Canon EOS R5 + 24-70mm f/2.8',
        tags: ['Pottery', 'Clay', 'Craftsmanship'],
      },
      {
        id: 'photo-cn-3',
        url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Scandinavian interior styling & ceramic dining objects',
        category: 'studio',
        aspectRatio: 'portrait',
        date: 'December 2025',
        location: 'Amsterdam Studio',
        cameraGear: 'Leica Q3 • 28mm f/1.7',
        tags: ['Interior Design', 'Ceramics', 'Minimalism'],
      },
      {
        id: 'photo-cn-4',
        url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
        caption: 'Artisan tea ritual & textured glazed vessels',
        category: 'lifestyle',
        aspectRatio: 'landscape',
        date: 'November 2025',
        location: 'Canal House, Amsterdam',
        cameraGear: 'Sony A7R V + 35mm f/1.4 GM',
        tags: ['Tea Ritual', 'Artisanal', 'Lifestyle'],
      },
    ],
    audience: {
      topCountries: [
        { country: 'Netherlands', percentage: 34 },
        { country: 'Germany', percentage: 30 },
        { country: 'United States', percentage: 22 },
        { country: 'UK', percentage: 14 },
      ],
      genderSplit: { female: 81, male: 19 },
      topAgeGroup: '22–35 Years (73%)',
    },
    reviews: [
      {
        id: 'rev-cn-1',
        brandName: 'IKEA Design',
        brandLogo: 'https://cdn.simpleicons.org/ikea/0A0A0A',
        rating: 5,
        comment: 'Chloe has a true Scandinavian design sensibility. Our collaborative posts achieved the highest bookmark rate on our feed.',
        campaignName: 'Autumn Ceramics Series',
        date: 'January 2026',
      },
      {
        id: 'rev-cn-2',
        brandName: 'Adobe Cloud',
        brandLogo: 'https://cdn.simpleicons.org/adobe/0A0A0A',
        rating: 5,
        comment: 'Her studio aesthetics elevated our tableware launch significantly. Super fast turnaround.',
        campaignName: 'Coffee Rituals',
        date: 'December 2025',
      },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-101',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&h=200&q=80',
    creatorId: 'creator-01',
    creatorName: 'Sophie Kim',
    creatorHandle: '@sophiekim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Instagram Reel Package',
    collaborationType: 'sponsored_post',
    platform: 'instagram',
    basePriceEur: 1200,
    platformFeeEur: 180,
    totalEur: 1380,
    status: 'in_production',
    brief: 'Create a 45s authentic evening skincare routine featuring our new Botanical Barrier Recovery Cream. Highlight natural scent and glass-skin glow.',
    requirements: [
      'Show bottle clearly in first 5 seconds',
      'Mention 100% cold-pressed rosehip seed extract',
      'Include exclusive discount code AURASOPHIE in caption',
    ],
    deadlineDate: '2026-03-28',
    createdAt: '2026-03-18',
    escrowFunded: true,
    escrowReleased: false,
    deliverables: [],
    messages: [
      {
        id: 'msg-1',
        senderId: 'user_brand_01',
        senderName: 'Elena (Aura Skincare)',
        senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=100&q=80',
        senderRole: 'brand',
        text: 'Hi Sophie! We are thrilled to partner with you. The PR package was delivered to your LA address yesterday.',
        timestamp: 'March 18, 10:15 AM',
      },
      {
        id: 'msg-2',
        senderId: 'creator-01',
        senderName: 'Sophie Kim',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        senderRole: 'creator',
        text: 'Got the package! The texture is gorgeous. I am filming the routine draft tomorrow afternoon.',
        timestamp: 'March 18, 11:30 AM',
      },
    ],
  },
  {
    id: 'ord-102',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&h=200&q=80',
    creatorId: 'creator-01',
    creatorName: 'Sophie Kim',
    creatorHandle: '@sophiekim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Organic UGC Ad Creative Pack',
    collaborationType: 'content_creation',
    platform: 'ugc',
    basePriceEur: 650,
    platformFeeEur: 97.5,
    totalEur: 747.5,
    status: 'deliverable_submitted',
    brief: 'Two 9:16 vertical hook variations testing "I stopped using foundation" vs "The only serum my dermatologist approved". Raw 4K files for Meta ad campaigns.',
    requirements: [
      'Hook variation 1: 0-3s bold statement with product in frame',
      'Hook variation 2: Natural bathroom mirror lighting demonstration',
      'Clean audio without background noise',
    ],
    deadlineDate: '2026-03-24',
    createdAt: '2026-03-14',
    escrowFunded: true,
    escrowReleased: false,
    deliverables: [
      {
        id: 'del-1',
        title: 'Hook_A_Serum_Routine_4K.mp4',
        previewUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
        submittedAt: 'March 19, 2026',
        notes: 'Filmed in 4K ProRes. Includes text safe zones for Instagram Reels and TikTok ads.',
      },
      {
        id: 'del-2',
        title: 'Hook_B_Bathroom_Mirror_4K.mp4',
        previewUrl: 'https://images.unsplash.com/photo-1608248597359-53530f2955cf?auto=format&fit=crop&w=600&q=80',
        submittedAt: 'March 19, 2026',
        notes: 'Alternative hook focusing on immediate glow effect.',
      },
    ],
    messages: [],
  },
  {
    id: 'ord-103',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&h=200&q=80',
    creatorId: 'creator-02',
    creatorName: 'Liam Carter',
    creatorHandle: '@liamcarter',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Cinematic Reel',
    collaborationType: 'sponsored_post',
    platform: 'instagram',
    basePriceEur: 1400,
    platformFeeEur: 210,
    totalEur: 1610,
    status: 'completed',
    brief: 'Showcasing our travel-size SPF 50 mineral mist during a Dolomites sunrise hike.',
    requirements: ['Show application during mountain summit view'],
    deadlineDate: '2026-03-10',
    createdAt: '2026-02-28',
    escrowFunded: true,
    escrowReleased: true,
    deliverables: [
      {
        id: 'del-3',
        title: 'Dolomites_Sunrise_SPF50_Live.mp4',
        livePostUrl: 'https://instagram.com/p/example',
        submittedAt: 'March 08, 2026',
      },
    ],
    messages: [],
    reviewSubmitted: {
      rating: 5,
      comment: 'Breathtaking footage! Liam is a true cinema professional.',
      date: 'March 10, 2026',
    },
  },
];

export const CATEGORIES_LIST = [
  { id: 'all', name: 'All Creators', count: 12430, icon: 'Grid' },
  { id: 'Beauty', name: 'Beauty', count: 1240, icon: 'Sparkles' },
  { id: 'Fashion', name: 'Fashion', count: 980, icon: 'Shirt' },
  { id: 'Fitness & Health', name: 'Fitness & Health', count: 1340, icon: 'Activity' },
  { id: 'Travel', name: 'Travel', count: 1120, icon: 'Compass' },
  { id: 'Food & Cuisine', name: 'Food & Cuisine', count: 890, icon: 'Utensils' },
  { id: 'Lifestyle', name: 'Lifestyle', count: 1560, icon: 'Coffee' },
  { id: 'Tech & Gaming', name: 'Tech & Gaming', count: 760, icon: 'Laptop' },
  { id: 'Business', name: 'Business', count: 420, icon: 'Briefcase' },
  { id: 'Art & Creativity', name: 'Art & Creativity', count: 680, icon: 'Palette' },
];

export const BRAND_FAQS = [
  {
    q: 'How does the Influverse escrow system protect my budget?',
    a: 'When a brand sends an offer, the campaign budget (creator rate + 15% platform fee) is placed into a secure escrow account. The creator starts working with complete confidence that funds are secured. Funds are only transferred to the creator once you review and approve the submitted content.',
  },
  {
    q: 'Why is Influverse different from traditional influencer agencies?',
    a: 'Influverse eliminates middleman markups, slow email chains, and opaque pricing. Brands get direct access to verified creator rate cards, 100% escrow milestone protection, on-demand portfolio previews, and automated EU VAT invoicing.',
  },
  {
    q: 'What is the difference between UGC Content and a Sponsored Post?',
    a: 'UGC (User Generated Content) is custom high-converting photo/video assets produced by the creator for your brand to run on your own official channels or paid ad campaigns. A Sponsored Post includes the creator publishing the content directly to their own engaged audience on Instagram, TikTok, or YouTube.',
  },
  {
    q: 'How do revisions work if I need changes on the content?',
    a: 'Each creator package includes specified revision rounds (typically 1 to 2 revisions). When a creator submits draft deliverables, you can request adjustments directly inside your order workspace with timestamped notes before final escrow sign-off.',
  },
  {
    q: 'Are all creators verified on Influverse?',
    a: 'Yes. Our talent team manually verifies creator identity, authentic audience engagement metrics, past brand collaborations, and channel handles across Instagram, TikTok, and YouTube before granting the verified checkmark badge.',
  },
  {
    q: 'What currencies and payment methods are supported?',
    a: 'All packages, custom offers, and balance transactions are standardized in EUR (€) with support for major credit cards (Visa, Mastercard, Amex), SEPA bank transfers, Apple Pay, and Google Pay.',
  },
  {
    q: 'How does VAT and invoice generation work for European businesses?',
    a: 'Influverse automatically generates compliant VAT invoices for every transaction. If your company is VAT-registered in the European Union, the reverse-charge mechanism is automatically applied at checkout.',
  },
  {
    q: 'What happens if a creator fails to deliver within the agreed deadline?',
    a: 'Every order features binding milestone deadlines. If a creator fails to submit content on time or misses communications, you have the right to cancel the campaign and receive a 100% escrow refund immediately.',
  },
];

export const CREATOR_FAQS = [
  {
    q: 'Do creators have to pay any fee or commission?',
    a: 'No. Creators keep 100% of their listed package price. The 15% platform fee is covered entirely by the hiring brand to fund escrow protection, contract guarantees, dispute mediation, and secure payouts.',
  },
  {
    q: 'When and how do I receive my earnings?',
    a: 'Payments are deposited into your Influverse wallet balance immediately after the brand reviews and approves your deliverables. You can withdraw your EUR balance directly to your bank account via SEPA or Stripe at any time.',
  },
  {
    q: 'How do I set my package prices and deliverable terms?',
    a: 'You have complete autonomy over your rate card. In your creator dashboard, you can define custom packages in EUR (€) for Instagram Reels, Stories, TikTok videos, YouTube integrations, and UGC bundles with your chosen turnaround times and revision limits.',
  },
  {
    q: 'Who owns the content rights and commercial usage license?',
    a: 'By default, organic sponsored posts allow brands organic reposting rights. If a brand wants paid advertising rights (whitelisting or dark ads), they must purchase commercial usage rights or choose a dedicated UGC package specified in your rate card.',
  },
  {
    q: 'What happens if a brand delays review or requests out-of-scope revisions?',
    a: 'Our platform includes auto-approval protection. If a brand does not review or request revisions within 5 days of submission, escrow funds are automatically released to your wallet. Our dedicated dispute team mediates any unreasonable requests.',
  },
  {
    q: 'Can I decline an offer if it does not match my personal brand?',
    a: 'Yes, 100%. You can review brand briefs, deliverables, guidelines, and timelines before accepting. You have full freedom to accept, decline, or send a custom counter-offer directly through the platform.',
  },
  {
    q: 'How do I get the Verified Creator badge on my profile?',
    a: 'Complete your profile setup, connect your active social channels (Instagram, TikTok, or YouTube) with verified audience metrics, and complete your first successful escrow collaboration with a 4.5+ rating.',
  },
  {
    q: 'Can I work with brands outside of my home country?',
    a: 'Yes! Influverse connects creators across Europe and internationally. All contracts and escrow payments are handled safely in EUR without international banking complications.',
  },
];

export const FAQS_LIST = BRAND_FAQS;

