import { Property, User, Lead, MarketInsight, Review } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_01',
    name: 'Alexander Sterling',
    email: 'alexander@luxuryliving.com',
    role: 'buyer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    phone: '+1 (310) 892-4411',
    location: 'Beverly Hills, California',
    bio: 'Private investor and luxury architecture enthusiast acquiring architectural estates.',
  },
  {
    id: 'agent_01',
    name: 'Sophia Vance',
    email: 'sophia@vancerealestate.com',
    role: 'agent',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    phone: '+1 (310) 555-0199',
    location: 'Los Angeles & Miami',
    agency: 'Vance Luxury Realty & Media',
    bio: 'Top 1% Global Producer & Real Estate Content Creator with over 1.8M followers across YouTube & Instagram.',
    socials: {
      instagram: '@sophiavancerealty',
      youtube: 'Sophia Vance Mansions',
      tiktok: '@sophia.vance.estates',
      linkedin: 'in/sophiavancerealtor',
    },
    rating: 4.98,
    reviewsCount: 142,
    salesVolume: '$420M+',
    activeListingsCount: 18,
  },
  {
    id: 'agent_02',
    name: 'Julian Montgomery',
    email: 'julian@montgomeryproperties.com',
    role: 'agent',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    phone: '+1 (212) 555-8833',
    location: 'New York & The Hamptons',
    agency: 'Manhattan Skyline Advisory',
    bio: 'High-end architectural advisor and TikTok real estate sensation specializing in ultra-luxury penthouses.',
    socials: {
      instagram: '@julian.montgomery.nyc',
      youtube: 'Julian NYC Real Estate',
      tiktok: '@juliannyc_estates',
    },
    rating: 4.95,
    reviewsCount: 98,
    salesVolume: '$310M+',
    activeListingsCount: 12,
  },
  {
    id: 'agent_03',
    name: 'Elena Rostova',
    email: 'elena@dubaiultra.com',
    role: 'agent',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    phone: '+971 4 888 1234',
    location: 'Dubai & London',
    agency: 'Palm & Mayfair Prime',
    bio: 'Celebrity broker and international keynote speaker presenting trophy assets worldwide.',
    socials: {
      instagram: '@elena_dubai_luxury',
      youtube: 'Elena Luxury Tours',
      tiktok: '@elenaluxuryliving',
    },
    rating: 5.0,
    reviewsCount: 86,
    salesVolume: '$580M+',
    activeListingsCount: 22,
  }
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'The Bellagio Crest Estate',
    tagline: 'Modern Architectural Masterpiece with 270° Panoramic City & Ocean Views',
    slug: 'the-bellagio-crest-estate',
    price: 24500000,
    priceFormatted: '$24,500,000',
    type: 'villa',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: '10480 Bellagio Road',
      city: 'Bel Air',
      state: 'California',
      country: 'USA',
      zipCode: '90077',
    },
    coordinates: {
      lat: 34.0837,
      lng: -118.4487,
    },
    specs: {
      bedrooms: 7,
      bathrooms: 11,
      sqft: 14500,
      garage: 6,
      yearBuilt: 2024,
      lotSize: '1.4 Acres',
    },
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'Perched high above Bel Air, The Bellagio Crest is a tour de force in modern luxury architecture. Designed with floor-to-ceiling motorized Fleetwood glass walls, zero-edge cantilevered infinity pool, temperature-controlled 1,200-bottle wine cellar, private screening theater, wellness spa with cold plunge & Finnish sauna, and full automated smart home integration.',
    amenities: [
      'Infinity Edge Pool',
      'Wellness Spa & Sauna',
      'Private Cinema Theater',
      '1,200 Bottle Wine Cellar',
      'Helipad Access',
      'Smart Home Automation',
      'Gourmet Chef Kitchen',
      'Gated Private Security',
      'Elevator Access',
      'Outdoor BBQ Pavilion',
    ],
    agent: {
      id: 'agent_01',
      name: 'Sophia Vance',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      title: 'Founding Partner & Luxury Director',
      phone: '+1 (310) 555-0199',
      email: 'sophia@vancerealestate.com',
      rating: 4.98,
      verified: true,
      socialFollowers: '1.8M Followers',
    },
    postedAt: '2026-03-10',
    viewsCount: 14850,
    savesCount: 620,
  },
  {
    id: 'prop-002',
    title: 'The Tribeca Sky Duplex',
    tagline: 'Crown Jewel Penthouse with 3,000 sqft Private Wrap-Around Terrace',
    slug: 'the-tribeca-sky-duplex',
    price: 18900000,
    priceFormatted: '$18,900,000',
    type: 'penthouse',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: '56 Leonard Street, PH 52',
      city: 'New York',
      state: 'New York',
      country: 'USA',
      zipCode: '10013',
    },
    coordinates: {
      lat: 40.7176,
      lng: -74.0068,
    },
    specs: {
      bedrooms: 5,
      bathrooms: 6,
      sqft: 8200,
      garage: 2,
      yearBuilt: 2023,
    },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'An iconic duplex penthouse hovering over Tribeca with unobstructed 360-degree views of the Hudson River, Midtown Skyline, and Statue of Liberty. Features 22-foot double height ceilings, custom Boffi kitchen, Calacatta marble fireplace, and private elevator landing.',
    amenities: [
      'Private Wrap-around Terrace',
      'Private Elevator Access',
      'Double Height 22ft Ceilings',
      '24/7 Doorman & Concierge',
      'Heated Outdoor Jacuzzi',
      'Bespoke Italian Kitchen',
      'Fitness Center & Pool',
      'Climate Control Storage',
    ],
    agent: {
      id: 'agent_02',
      name: 'Julian Montgomery',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
      title: 'Principal Luxury Broker',
      phone: '+1 (212) 555-8833',
      email: 'julian@montgomeryproperties.com',
      rating: 4.95,
      verified: true,
      socialFollowers: '920K Followers',
    },
    postedAt: '2026-03-12',
    viewsCount: 22400,
    savesCount: 940,
  },
  {
    id: 'prop-003',
    title: 'Villa Riviera Palm Oasis',
    tagline: 'Direct Oceanfront Private Beach Villa on Palm Jumeirah Frond G',
    slug: 'villa-riviera-palm-oasis',
    price: 32000000,
    priceFormatted: '$32,000,000',
    type: 'villa',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: 'Frond G, Palm Jumeirah',
      city: 'Dubai',
      state: 'Dubai',
      country: 'UAE',
      zipCode: '00000',
    },
    coordinates: {
      lat: 25.1124,
      lng: 55.1390,
    },
    specs: {
      bedrooms: 6,
      bathrooms: 8,
      sqft: 16800,
      garage: 4,
      yearBuilt: 2025,
      lotSize: '20,000 sqft',
    },
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'Experience ultra-prime Dubai luxury on the prestigious Frond G of Palm Jumeirah. Private sandy beach access, 80-foot beachfront pool, imported Italian Travertine marble, bespoke Poliform furniture, staff quarters, and rooftop lounge overlooking Dubai Marina skyline.',
    amenities: [
      'Private Beachfront Access',
      'Private Yacht Mooring',
      'Rooftop Marina Skyline Lounge',
      'Poliform Italian Furnishings',
      'Staff & Driver Quarters',
      'Olympic-length Pool',
      'Smart Biometric Security',
      'Private Spa & Hamam',
    ],
    agent: {
      id: 'agent_03',
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
      title: 'International Partner',
      phone: '+971 4 888 1234',
      email: 'elena@dubaiultra.com',
      rating: 5.0,
      verified: true,
      socialFollowers: '2.4M Followers',
    },
    postedAt: '2026-03-01',
    viewsCount: 38100,
    savesCount: 1420,
  },
  {
    id: 'prop-004',
    title: 'Star Island Modern Waterfront',
    tagline: 'Ultra-Modern Architectural Compound with 100ft Deepwater Dock',
    slug: 'star-island-modern-waterfront',
    price: 45000000,
    priceFormatted: '$45,000,000',
    type: 'mansion',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: '22 Star Island Drive',
      city: 'Miami Beach',
      state: 'Florida',
      country: 'USA',
      zipCode: '33139',
    },
    coordinates: {
      lat: 25.7781,
      lng: -80.1511,
    },
    specs: {
      bedrooms: 8,
      bathrooms: 12,
      sqft: 18500,
      garage: 8,
      yearBuilt: 2024,
      lotSize: '1.1 Acres',
    },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'The pinnacle of Miami Beach elite living. Located in guard-gated Star Island, this estate features 100ft of deepwater frontage capable of docking mega-yachts, glass bridge foyer, 2-tier resort swimming pool, tennis court, and guest house.',
    amenities: [
      'Mega-Yacht Deepwater Dock',
      'Championship Tennis Court',
      'Guard Gated Island',
      'Separate Guest House',
      'Two-Tier Resort Pool',
      'Commercial Grade Elevator',
      'Sub-Zero & Wolf Appliances',
      'Full Gym & Steam Room',
    ],
    agent: {
      id: 'agent_01',
      name: 'Sophia Vance',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      title: 'Founding Partner & Luxury Director',
      phone: '+1 (310) 555-0199',
      email: 'sophia@vancerealestate.com',
      rating: 4.98,
      verified: true,
      socialFollowers: '1.8M Followers',
    },
    postedAt: '2026-03-05',
    viewsCount: 29500,
    savesCount: 1150,
  },
  {
    id: 'prop-005',
    title: 'The Knightsbridge Mews House',
    tagline: 'Timeless Victorian Elegance reimagined with Contemporary Finishes',
    slug: 'the-knightsbridge-mews-house',
    price: 14200000,
    priceFormatted: '£11,200,000 ($14.2M)',
    type: 'townhouse',
    status: 'for_sale',
    isFeatured: false,
    isVerified: true,
    address: {
      street: '14 Rutland Mews South',
      city: 'London',
      state: 'Greater London',
      country: 'UK',
      zipCode: 'SW7 1NZ',
    },
    coordinates: {
      lat: 51.5014,
      lng: -0.1654,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 5,
      sqft: 4800,
      garage: 2,
      yearBuilt: 2022,
    },
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: false,
    description: 'Discreet luxury moments from Hyde Park and Harrods. Features an integrated subterranean car stacker, swimming pool, bespoke French oak chevron floors, and automated climate control.',
    amenities: [
      'Subterranean Swimming Pool',
      'Hydraulic Car Lift Stacker',
      'Chevron Hardwood Flooring',
      'Private Wine Tasting Cellar',
      'Proximity to Harrods & Hyde Park',
      'Air Conditioning throughout',
    ],
    agent: {
      id: 'agent_03',
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
      title: 'International Partner',
      phone: '+971 4 888 1234',
      email: 'elena@dubaiultra.com',
      rating: 5.0,
      verified: true,
      socialFollowers: '2.4M Followers',
    },
    postedAt: '2026-03-08',
    viewsCount: 16200,
    savesCount: 540,
  },
  {
    id: 'prop-006',
    title: 'Red Mountain Ski Chalet',
    tagline: 'Ski-In / Ski-Out Luxury Lodge with Heated Granite Terraces & Mountain Vistas',
    slug: 'red-mountain-ski-chalet',
    price: 21500000,
    priceFormatted: '$21,500,000',
    type: 'villa',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: '720 Red Mountain Road',
      city: 'Aspen',
      state: 'Colorado',
      country: 'USA',
      zipCode: '81611',
    },
    coordinates: {
      lat: 39.1911,
      lng: -106.8175,
    },
    specs: {
      bedrooms: 6,
      bathrooms: 8,
      sqft: 9800,
      garage: 3,
      yearBuilt: 2023,
      lotSize: '2.2 Acres',
    },
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'Ultimate alpine indulgence on Aspen Red Mountain. Direct ski-in ski-out trail access, heated driveways, cedar hot tub overlooking Ajax Mountain, custom timber beams, and ski locker room with boot warmers.',
    amenities: [
      'Ski-In / Ski-Out Access',
      'Heated Granite Terraces',
      'Outdoor Cedar Hot Tub',
      'Ski Locker Room with Boot Warmers',
      'Stone Fireplaces throughout',
      'Heated Driveway & Walkways',
      'Custom Wine Wall',
    ],
    agent: {
      id: 'agent_02',
      name: 'Julian Montgomery',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
      title: 'Principal Luxury Broker',
      phone: '+1 (212) 555-8833',
      email: 'julian@montgomeryproperties.com',
      rating: 4.95,
      verified: true,
      socialFollowers: '920K Followers',
    },
    postedAt: '2026-02-28',
    viewsCount: 19800,
    savesCount: 780,
  },
  {
    id: 'prop-007',
    title: 'The Glass Pavilion Luxury Condo',
    tagline: 'Modernist Masterwork with Floor-to-Ceiling Glass & Private Pool',
    slug: 'the-glass-pavilion-luxury-condo',
    price: 8900000,
    priceFormatted: '$8,900,000',
    type: 'apartment',
    status: 'for_sale',
    isFeatured: false,
    isVerified: true,
    address: {
      street: '1100 Ocean Drive, Penthouse 4',
      city: 'Miami Beach',
      state: 'Florida',
      country: 'USA',
      zipCode: '33139',
    },
    coordinates: {
      lat: 25.7825,
      lng: -80.1300,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 4,
      sqft: 3950,
      garage: 2,
      yearBuilt: 2024,
    },
    images: [
      'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'South Beach luxury condo offering turnkey designer furnishings, infinity plunge pool on balcony, valet parking, and 24hr white glove concierge.',
    amenities: [
      'Balcony Plunge Pool',
      'White Glove Concierge',
      'Turnkey Designer Furniture',
      'Valet Parking',
      'Direct Beach Access',
    ],
    agent: {
      id: 'agent_01',
      name: 'Sophia Vance',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      title: 'Founding Partner & Luxury Director',
      phone: '+1 (310) 555-0199',
      email: 'sophia@vancerealestate.com',
      rating: 4.98,
      verified: true,
      socialFollowers: '1.8M Followers',
    },
    postedAt: '2026-03-14',
    viewsCount: 11200,
    savesCount: 390,
  },
  {
    id: 'prop-008',
    title: 'Monaco Harbor Villa Penthouse',
    tagline: 'Front-Row Grand Prix & Superyacht Harbor View Residence',
    slug: 'monaco-harbor-villa-penthouse',
    price: 38000000,
    priceFormatted: '€35,000,000 ($38M)',
    type: 'penthouse',
    status: 'for_sale',
    isFeatured: true,
    isVerified: true,
    address: {
      street: 'Avenue Princesse Grace',
      city: 'Monte Carlo',
      state: 'Monaco',
      country: 'Monaco',
      zipCode: '98000',
    },
    coordinates: {
      lat: 43.7384,
      lng: 7.4246,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 6,
      sqft: 6200,
      garage: 3,
      yearBuilt: 2023,
    },
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    ],
    videoTourUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour3D: true,
    description: 'Rare trophy penthouse overlooking Port Hercule. Private swimming pool on rooftop terrace, bespoke finishes by world-renowned interior designers, and unmatched security.',
    amenities: [
      'F1 Grand Prix Track View',
      'Superyacht Port Hercule Views',
      'Private Rooftop Pool',
      'Bespoke Italian Craftsmanship',
      'Secure Triple Garage',
    ],
    agent: {
      id: 'agent_03',
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
      title: 'International Partner',
      phone: '+971 4 888 1234',
      email: 'elena@dubaiultra.com',
      rating: 5.0,
      verified: true,
      socialFollowers: '2.4M Followers',
    },
    postedAt: '2026-03-02',
    viewsCount: 41200,
    savesCount: 1650,
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-101',
    clientName: 'Lord Harrison Sterling',
    clientEmail: 'harrison.sterling@sterlingcap.co.uk',
    clientPhone: '+44 20 7946 0912',
    clientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    propertyId: 'prop-001',
    propertyTitle: 'The Bellagio Crest Estate',
    propertyPrice: '$24,500,000',
    propertyImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80',
    message: 'Seeking a private confidential viewing this Thursday afternoon with my acquisition counsel.',
    preferredDate: '2026-03-22',
    status: 'new',
    createdAt: '2026-03-18 10:30 AM',
    budgetRange: '$20M - $30M',
    notes: 'Pre-qualified with JP Morgan Private Bank. Interested in immediate escrow.',
  },
  {
    id: 'lead-102',
    clientName: 'Dr. Camille Fontaine',
    clientEmail: 'camille@fontainemedical.com',
    clientPhone: '+1 (305) 555-4421',
    clientAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
    propertyId: 'prop-004',
    propertyTitle: 'Star Island Modern Waterfront',
    propertyPrice: '$45,000,000',
    propertyImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=400&q=80',
    message: 'We are expanding our estate footprint in South Florida and require deepwater dock specifications.',
    preferredDate: '2026-03-24',
    status: 'contacted',
    createdAt: '2026-03-17 03:15 PM',
    budgetRange: '$40M - $50M',
    notes: 'Requires 120ft yacht clearance verification.',
  },
  {
    id: 'lead-103',
    clientName: 'Marcus & Chloe Vance',
    clientEmail: 'marcus@vancetech.io',
    clientPhone: '+1 (415) 555-8790',
    clientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    propertyId: 'prop-002',
    propertyTitle: 'The Tribeca Sky Duplex',
    propertyPrice: '$18,900,000',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    message: 'Love the video tour Sophia posted on YouTube! Ready to schedule our second walk-through.',
    preferredDate: '2026-03-21',
    status: 'viewing_scheduled',
    createdAt: '2026-03-16 11:00 AM',
    budgetRange: '$15M - $20M',
    notes: 'Contract draft sent to legal team.',
  },
  {
    id: 'lead-104',
    clientName: 'Sheikh Tariq Al-Mansoor',
    clientEmail: 'tariq@almansoorgroup.ae',
    clientPhone: '+971 50 123 4567',
    clientAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    propertyId: 'prop-003',
    propertyTitle: 'Villa Riviera Palm Oasis',
    propertyPrice: '$32,000,000',
    propertyImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=400&q=80',
    message: 'Offer submitted via wire escrow deposit.',
    preferredDate: '2026-03-15',
    status: 'offer_made',
    createdAt: '2026-03-14 09:20 AM',
    budgetRange: '$30M+',
    notes: 'Escrow verification complete.',
  },
];

export const MOCK_MARKET_INSIGHTS: MarketInsight[] = [
  {
    id: 'insight-1',
    title: 'How Ultra-Luxury Real Estate Influencers Are Shifting Global Capital in 2026',
    category: 'Market Trends',
    readTime: '5 min read',
    publishDate: 'March 16, 2026',
    author: 'Sophia Vance',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    summary: 'Video walkthroughs and architectural media storytelling generate over 64% of international high-net-worth acquisitions before buyer arrival.',
    views: '24.8K',
  },
  {
    id: 'insight-2',
    title: 'The Rise of Smart Wellness Amenities in Architectural Penthouses',
    category: 'Architecture & Design',
    readTime: '4 min read',
    publishDate: 'March 12, 2026',
    author: 'Julian Montgomery',
    authorAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    summary: 'Cold plunges, circadian lighting systems, and private hyperbaric chambers command a 18% premium in Manhattan and Miami listings.',
    views: '18.3K',
  },
  {
    id: 'insight-3',
    title: 'Dubai Trophy Assets: Frond G and Jumeirah Bay Island Deep Dive',
    category: 'Global Investments',
    readTime: '6 min read',
    publishDate: 'March 08, 2026',
    author: 'Elena Rostova',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    summary: 'Analyzing year-over-year capital gains and why billionaire families are prioritizing freehold waterfront compounds.',
    views: '31.2K',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    userName: 'Sebastian Cole',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    userRole: 'Tech Founder & Buyer',
    rating: 5,
    comment: 'Sophia and her team made acquiring our Bel Air estate seamless. Her YouTube walkthrough highlighted every architectural detail, and negotiations were handled with supreme discretion.',
    date: 'February 2026',
    propertyTitle: 'The Bellagio Crest Estate',
  },
  {
    id: 'rev-2',
    userName: 'Victoria DeLuca',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    userRole: 'Private Wealth Investor',
    rating: 5,
    comment: 'Julian Montgomery has his finger on the pulse of Manhattan luxury. He secured our Tribeca duplex off-market before it hit public listing portals.',
    date: 'January 2026',
    propertyTitle: 'The Tribeca Sky Duplex',
  },
  {
    id: 'rev-3',
    userName: 'Mateo Rossi',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    userRole: 'Real Estate Developer',
    rating: 5,
    comment: 'The reach Elena has across Dubai and London is unmatched. Over 300K views in 48 hours for our waterfront development.',
    date: 'March 2026',
    propertyTitle: 'Villa Riviera Palm Oasis',
  },
];

export const PROPERTY_CATEGORIES = [
  {
    name: 'Modern Villas',
    count: '48 Properties',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
    type: 'villa',
    slug: 'villa',
  },
  {
    name: 'Sky Penthouses',
    count: '32 Properties',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    type: 'penthouse',
    slug: 'penthouse',
  },
  {
    name: 'Beachfront Estates',
    count: '24 Properties',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    type: 'mansion',
    slug: 'mansion',
  },
  {
    name: 'Luxury Condos',
    count: '56 Properties',
    image: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80',
    type: 'apartment',
    slug: 'apartment',
  },
  {
    name: 'Historic Townhouses',
    count: '19 Properties',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    type: 'townhouse',
    slug: 'townhouse',
  },
];

export const AGENT_ANALYTICS = {
  monthlyViews: [
    { month: 'Oct', views: 42000, inquiries: 180 },
    { month: 'Nov', views: 58000, inquiries: 240 },
    { month: 'Dec', views: 64000, inquiries: 290 },
    { month: 'Jan', views: 79000, inquiries: 360 },
    { month: 'Feb', views: 95000, inquiries: 440 },
    { month: 'Mar', views: 124000, inquiries: 580 },
  ],
  trafficSources: [
    { source: 'YouTube Video Tours', percentage: 44 },
    { source: 'Instagram / Reels', percentage: 28 },
    { source: 'Direct Website Search', percentage: 18 },
    { source: 'TikTok & Short Form', percentage: 10 },
  ],
  topPerformingListings: [
    { title: 'The Bellagio Crest Estate', views: '48.5K', leads: 42, conversion: '3.8%' },
    { title: 'Star Island Modern Waterfront', views: '38.2K', leads: 31, conversion: '3.4%' },
    { title: 'The Tribeca Sky Duplex', views: '29.1K', leads: 28, conversion: '4.1%' },
    { title: 'Villa Riviera Palm Oasis', views: '52.4K', leads: 49, conversion: '4.5%' },
  ]
};
