import { Creator, User, Order } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_brand_01',
    name: 'Elena Rostova',
    email: 'elena@aura-cosmetics.com',
    role: 'brand',
    companyName: 'Aura Skincare Paris',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    location: 'Berlin & Paris',
    bio: 'Brand Lead at Aura Skincare developing organic beauty and wellness product launches.',
    balanceEur: 8450,
  },
  {
    id: 'user_creator_01',
    name: 'Sophie Kim',
    email: 'sophie@sophiekim.com',
    role: 'creator',
    handle: '@sophiekim',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    location: 'Los Angeles, CA',
    bio: 'I create authentic, relatable content about beauty, wellness and everyday life. I love working with brands that share my values and believe in meaningful, long-term partnerships.',
    balanceEur: 3200,
  },
];

export const MOCK_CREATORS: Creator[] = [
  {
    id: 'creator-01',
    name: 'Sophie Kim',
    handle: 'sophiekim',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    bio: 'I create authentic, relatable content about beauty, wellness and everyday life. I love working with brands that share my values and believe in meaningful, long-term partnerships.',
    location: 'Los Angeles, CA',
    verified: true,
    categories: ['Beauty', 'Lifestyle', 'Fashion'],
    tags: ['Beauty', 'Lifestyle', 'Self Care', 'Skincare', 'Wellness'],
    platforms: {
      instagram: {
        followers: 1200000,
        followersFormatted: '1.2M',
        handle: '@sophiekim',
        engagementRate: '4.8%',
        avgViews: '240K',
      },
      tiktok: {
        followers: 680000,
        followersFormatted: '680K',
        handle: '@sophie.kim',
        engagementRate: '6.2%',
        avgViews: '410K',
      },
      youtube: {
        followers: 210000,
        followersFormatted: '210K',
        handle: 'Sophie Kim Vlogs',
        engagementRate: '8.4%',
        avgViews: '95K',
      },
      ugc: {
        avgDelivery: '3 Days',
        turnaround: '48h Rush Available',
      },
    },
    startingPriceEur: 500,
    rating: 4.98,
    reviewsCount: 42,
    totalCollaborations: 128,
    packages: [
      {
        id: 'pkg-sk-1',
        platform: 'instagram',
        title: 'Story Package',
        type: 'story',
        description: 'A set of 3–5 Instagram Stories with product integration, direct link sticker and brand mention.',
        priceEur: 500,
        deliveryDays: 3,
        revisions: 1,
        inclusions: ['3x Stories', 'Link Sticker', 'Brand Tag', '24h Analytics Screenshot'],
      },
      {
        id: 'pkg-sk-2',
        platform: 'instagram',
        title: 'Reel Package',
        type: 'reel',
        description: 'A 15–60 second Instagram Reel featuring your product in an authentic and creative way.',
        priceEur: 1200,
        deliveryDays: 5,
        revisions: 2,
        inclusions: ['1x 60s Reel', 'Original Audio/Voiceover', 'Product Tagging', '30-Day Organic Rights'],
      },
      {
        id: 'pkg-sk-3',
        platform: 'instagram',
        title: 'Feed Post Package',
        type: 'post',
        description: 'A high-quality Instagram post with thoughtful caption, carousel images, and brand integration.',
        priceEur: 800,
        deliveryDays: 4,
        revisions: 1,
        inclusions: ['1x Carousel Post (up to 4 slides)', 'Dedicated Caption', 'Brand Tag'],
      },
      {
        id: 'pkg-sk-4',
        platform: 'tiktok',
        title: 'Dedicated TikTok Video',
        type: 'video',
        description: 'Engaging 30–60 second TikTok with trending audio, natural demonstration and sound integration.',
        priceEur: 950,
        deliveryDays: 4,
        revisions: 2,
        inclusions: ['1x TikTok Video', 'Hook testing', 'Pinned Comment', 'Commercial Music Sync'],
      },
      {
        id: 'pkg-sk-5',
        platform: 'ugc',
        title: 'Organic UGC Ad Creative Pack',
        type: 'ugc_video',
        description: 'Two raw vertical 9:16 video variations (Hook A & B) filmed with 4K camera with paid media licensing.',
        priceEur: 650,
        deliveryDays: 3,
        revisions: 2,
        inclusions: ['2x Hook Variations', 'Raw 4K Footage', 'Full Paid Ad Rights (90 Days)'],
      },
    ],
    portfolio: [
      {
        id: 'port-1',
        brandName: 'Laneige',
        campaignTitle: 'Skincare Campaign',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
        views: '320K',
        likes: '28.4K',
        platform: 'instagram',
      },
      {
        id: 'port-2',
        brandName: 'The Ordinary',
        campaignTitle: 'Product Feature & Routine',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1608248597359-53530f2955cf?auto=format&fit=crop&w=600&q=80',
        views: '410K',
        likes: '34.1K',
        platform: 'tiktok',
      },
      {
        id: 'port-3',
        brandName: 'Sephora',
        campaignTitle: 'A Day in My Life Essentials',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
        views: '540K',
        likes: '49.2K',
        platform: 'youtube',
      },
      {
        id: 'port-4',
        brandName: 'OUAI',
        campaignTitle: 'Hair & Body UGC Content',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80',
        views: '280K',
        likes: '21.9K',
        platform: 'ugc',
      },
    ],
    audience: {
      topCountries: [
        { country: 'United States', percentage: 46 },
        { country: 'Germany & DACH', percentage: 22 },
        { country: 'United Kingdom', percentage: 18 },
        { country: 'France', percentage: 14 },
      ],
      genderSplit: { female: 78, male: 22 },
      topAgeGroup: '22–34 Years (64%)',
    },
    reviews: [
      {
        id: 'rev-1',
        brandName: 'Laneige Global',
        brandLogo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=100&q=80',
        rating: 5,
        comment: 'Sophie delivered extraordinary work! Her Reel generated over 300k views in 48 hours and drove a remarkable 4.2x ROAS for our launch.',
        campaignName: 'Hydration Serum Drop',
        date: 'February 2026',
      },
      {
        id: 'rev-2',
        brandName: 'Aura Skincare',
        brandLogo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=100&q=80',
        rating: 5,
        comment: 'Punctual, professional, and clear communication. The raw UGC content was shot impeccably.',
        campaignName: 'Organic Cleanser UGC',
        date: 'January 2026',
      },
    ],
  },
  {
    id: 'creator-02',
    name: 'Liam Carter',
    handle: 'liamcarter',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    bio: 'Cinematic travel filmmaker and outdoor adventurer. Sharing journeys through the Alps, Scandinavia and remote coastal locations.',
    location: 'Munich, Germany',
    verified: true,
    categories: ['Travel', 'Outdoor', 'Lifestyle'],
    tags: ['Travel', 'Adventure', 'Outdoors', 'Photography', 'Vanlife'],
    platforms: {
      instagram: {
        followers: 980000,
        followersFormatted: '980K',
        handle: '@liam.carter.travel',
        engagementRate: '5.4%',
        avgViews: '310K',
      },
      tiktok: {
        followers: 650000,
        followersFormatted: '650K',
        handle: '@liamcarter',
        engagementRate: '7.1%',
        avgViews: '490K',
      },
      youtube: {
        followers: 230000,
        followersFormatted: '230K',
        handle: 'Liam Carter Cinema',
        engagementRate: '9.2%',
        avgViews: '120K',
      },
    },
    startingPriceEur: 650,
    rating: 4.96,
    reviewsCount: 38,
    totalCollaborations: 94,
    packages: [
      {
        id: 'pkg-lc-1',
        platform: 'instagram',
        title: 'Cinematic Reel',
        type: 'reel',
        description: 'Drone and cinema camera 4K video capturing your outdoor/apparel gear in breathtaking landscapes.',
        priceEur: 1400,
        deliveryDays: 6,
        revisions: 2,
        inclusions: ['4K Cinema Camera + FPV Drone', 'Color Graded', 'Audio Sync', 'Brand Tag'],
      },
      {
        id: 'pkg-lc-2',
        platform: 'tiktok',
        title: 'Adventure Story Video',
        type: 'video',
        description: 'High-energy storytelling video on TikTok testing your gear on an expedition.',
        priceEur: 850,
        deliveryDays: 4,
        revisions: 1,
        inclusions: ['1x TikTok', 'Voiceover Story', 'Product Link in Bio'],
      },
    ],
    portfolio: [
      {
        id: 'port-lc-1',
        brandName: 'Arc\'teryx',
        campaignTitle: 'Alpine Expedition Series',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=600&q=80',
        views: '480K',
        likes: '39K',
        platform: 'instagram',
      },
    ],
    audience: {
      topCountries: [
        { country: 'Germany', percentage: 38 },
        { country: 'Austria & Switzerland', percentage: 24 },
        { country: 'United States', percentage: 20 },
        { country: 'UK', percentage: 18 },
      ],
      genderSplit: { female: 35, male: 65 },
      topAgeGroup: '25–40 Years (71%)',
    },
    reviews: [],
  },
  {
    id: 'creator-03',
    name: 'Maya Chen',
    handle: 'mayachen',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    bio: 'Certified strength trainer and holistic wellness advocate. Helping over 2M+ followers build sustainable habits and athletic performance.',
    location: 'London, UK',
    verified: true,
    categories: ['Fitness', 'Health', 'Lifestyle'],
    tags: ['Fitness', 'Wellness', 'Nutrition', 'Athleisure', 'Mental Health'],
    platforms: {
      instagram: {
        followers: 1400000,
        followersFormatted: '1.4M',
        handle: '@maya.chen.fit',
        engagementRate: '5.1%',
        avgViews: '380K',
      },
      tiktok: {
        followers: 920000,
        followersFormatted: '920K',
        handle: '@mayachen',
        engagementRate: '6.8%',
        avgViews: '620K',
      },
      youtube: {
        followers: 410000,
        followersFormatted: '410K',
        handle: 'Maya Chen Fitness',
        engagementRate: '7.9%',
        avgViews: '180K',
      },
    },
    startingPriceEur: 750,
    rating: 5.0,
    reviewsCount: 56,
    totalCollaborations: 160,
    packages: [
      {
        id: 'pkg-mc-1',
        platform: 'instagram',
        title: 'Workout Reel & Story Combo',
        type: 'reel',
        description: 'Full workout integration wearing/using your product with swipe-up links and story series.',
        priceEur: 1600,
        deliveryDays: 5,
        revisions: 2,
        inclusions: ['1x Feed Reel', '3x Story Follow-ups', 'Direct Link in Story', '30-Day Rights'],
      },
    ],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'United Kingdom', percentage: 42 },
        { country: 'United States', percentage: 28 },
        { country: 'Germany', percentage: 16 },
        { country: 'Australia', percentage: 14 },
      ],
      genderSplit: { female: 68, male: 32 },
      topAgeGroup: '20–35 Years (76%)',
    },
    reviews: [],
  },
  {
    id: 'creator-04',
    name: 'Noah Becker',
    handle: 'noahbecker',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    bio: 'Contemporary menswear stylist and creative director. Curating clean minimalist aesthetics and capsule wardrobes.',
    location: 'Berlin, Germany',
    verified: true,
    categories: ['Fashion', 'Lifestyle', 'Men\'s Style'],
    tags: ['Fashion', 'Streetwear', 'Tailoring', 'Minimalism', 'Grooming'],
    platforms: {
      instagram: {
        followers: 520000,
        followersFormatted: '520K',
        handle: '@noah.becker',
        engagementRate: '4.6%',
        avgViews: '140K',
      },
      tiktok: {
        followers: 310000,
        followersFormatted: '310K',
        handle: '@noahbeckerstyle',
        engagementRate: '5.9%',
        avgViews: '210K',
      },
      youtube: {
        followers: 180000,
        followersFormatted: '180K',
        handle: 'Noah Becker Style',
        engagementRate: '6.5%',
        avgViews: '80K',
      },
    },
    startingPriceEur: 450,
    rating: 4.94,
    reviewsCount: 29,
    totalCollaborations: 72,
    packages: [
      {
        id: 'pkg-nb-1',
        platform: 'instagram',
        title: 'Editorial Outfit Carousel',
        type: 'post',
        description: 'Studio & street-style photography showcasing your garments in 4 distinct styled looks.',
        priceEur: 750,
        deliveryDays: 4,
        revisions: 1,
        inclusions: ['4x High-Res Retouched Stills', 'Lookbook Styling', 'Tag in Image & Caption'],
      },
    ],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'Germany', percentage: 52 },
        { country: 'France', percentage: 18 },
        { country: 'Netherlands', percentage: 15 },
        { country: 'UK', percentage: 15 },
      ],
      genderSplit: { female: 28, male: 72 },
      topAgeGroup: '22–38 Years (69%)',
    },
    reviews: [],
  },
  {
    id: 'creator-05',
    name: 'Emma Rossi',
    handle: 'emmarossi',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Pastry chef and culinary creator crafting approachable gourmet recipes, kitchen equipment tests, and dining guides.',
    location: 'Milan & Zurich',
    verified: true,
    categories: ['Food', 'Cuisine', 'Lifestyle'],
    tags: ['Food', 'Recipes', 'Baking', 'Kitchen Appliances', 'Wine'],
    platforms: {
      instagram: {
        followers: 850000,
        followersFormatted: '850K',
        handle: '@emmarossi.table',
        engagementRate: '5.8%',
        avgViews: '290K',
      },
      tiktok: {
        followers: 390000,
        followersFormatted: '390K',
        handle: '@emmarossicooks',
        engagementRate: '6.4%',
        avgViews: '380K',
      },
      youtube: {
        followers: 120000,
        followersFormatted: '120K',
        handle: 'Emma Rossi Kitchen',
        engagementRate: '8.1%',
        avgViews: '70K',
      },
    },
    startingPriceEur: 550,
    rating: 4.97,
    reviewsCount: 33,
    totalCollaborations: 85,
    packages: [],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'Italy', percentage: 40 },
        { country: 'Germany & Switzerland', percentage: 32 },
        { country: 'France', percentage: 28 },
      ],
      genderSplit: { female: 72, male: 28 },
      topAgeGroup: '24–45 Years (68%)',
    },
    reviews: [],
  },
  {
    id: 'creator-06',
    name: 'Daniel Park',
    handle: 'danielpark',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Software engineer and desk setup enthusiast reviewing developer tools, productivity gadgets, and AI hardware.',
    location: 'San Francisco, CA',
    verified: true,
    categories: ['Tech', 'Gaming', 'Business'],
    tags: ['Tech', 'Gadgets', 'Productivity', 'Desk Setup', 'AI Tools'],
    platforms: {
      instagram: {
        followers: 620000,
        followersFormatted: '620K',
        handle: '@danielpark.tech',
        engagementRate: '4.2%',
        avgViews: '190K',
      },
      tiktok: {
        followers: 790000,
        followersFormatted: '790K',
        handle: '@danielparktech',
        engagementRate: '7.8%',
        avgViews: '550K',
      },
      youtube: {
        followers: 340000,
        followersFormatted: '340K',
        handle: 'Daniel Park Tech',
        engagementRate: '8.6%',
        avgViews: '140K',
      },
    },
    startingPriceEur: 600,
    rating: 4.99,
    reviewsCount: 47,
    totalCollaborations: 110,
    packages: [],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'United States', percentage: 54 },
        { country: 'Germany', percentage: 18 },
        { country: 'Canada', percentage: 15 },
        { country: 'UK', percentage: 13 },
      ],
      genderSplit: { female: 18, male: 82 },
      topAgeGroup: '18–35 Years (81%)',
    },
    reviews: [],
  },
  {
    id: 'creator-07',
    name: 'Isabella Torres',
    handle: 'isabellatorres',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Sun-drenched Mediterranean lifestyle, boutique resort showcases, and sustainable summer fashion.',
    location: 'Barcelona, Spain',
    verified: true,
    categories: ['Travel', 'Lifestyle', 'Fashion'],
    tags: ['Travel', 'Resorts', 'Bikinis', 'Summer Style', 'Hotel Reviews'],
    platforms: {
      instagram: {
        followers: 670000,
        followersFormatted: '670K',
        handle: '@isabella.torres',
        engagementRate: '5.2%',
        avgViews: '220K',
      },
      tiktok: {
        followers: 480000,
        followersFormatted: '480K',
        handle: '@isabellatorres',
        engagementRate: '6.0%',
        avgViews: '310K',
      },
      youtube: {
        followers: 210000,
        followersFormatted: '210K',
        handle: 'Isabella Summer Diaries',
        engagementRate: '7.4%',
        avgViews: '90K',
      },
    },
    startingPriceEur: 500,
    rating: 4.95,
    reviewsCount: 31,
    totalCollaborations: 78,
    packages: [],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'Spain', percentage: 36 },
        { country: 'Germany & DACH', percentage: 28 },
        { country: 'UK', percentage: 20 },
        { country: 'France', percentage: 16 },
      ],
      genderSplit: { female: 74, male: 26 },
      topAgeGroup: '20–32 Years (75%)',
    },
    reviews: [],
  },
  {
    id: 'creator-08',
    name: 'Chloe Nguyen',
    handle: 'chloenguyen',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
    bio: 'Visual artist and interior designer transforming everyday spaces through thoughtful ceramics, paintings, and studio vlogs.',
    location: 'Amsterdam, Netherlands',
    verified: true,
    categories: ['Art', 'Creativity', 'Lifestyle'],
    tags: ['Art', 'Ceramics', 'Design', 'Studio Life', 'Interior'],
    platforms: {
      instagram: {
        followers: 420000,
        followersFormatted: '420K',
        handle: '@chloe.nguyen.art',
        engagementRate: '6.7%',
        avgViews: '180K',
      },
      tiktok: {
        followers: 310000,
        followersFormatted: '310K',
        handle: '@chloeartstudio',
        engagementRate: '8.2%',
        avgViews: '290K',
      },
      youtube: {
        followers: 150000,
        followersFormatted: '150K',
        handle: 'Chloe Nguyen Studio',
        engagementRate: '9.0%',
        avgViews: '85K',
      },
    },
    startingPriceEur: 400,
    rating: 4.98,
    reviewsCount: 26,
    totalCollaborations: 64,
    packages: [],
    portfolio: [],
    audience: {
      topCountries: [
        { country: 'Netherlands', percentage: 34 },
        { country: 'Germany', percentage: 30 },
        { country: 'United States', percentage: 22 },
        { country: 'UK', percentage: 14 },
      ],
      genderSplit: { female: 81, male: 19 },
      topAgeGroup: '22–35 Years (73%)',
    },
    reviews: [],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-101',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=100&q=80',
    creatorId: 'creator-01',
    creatorName: 'Sophie Kim',
    creatorHandle: '@sophiekim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Instagram Reel Package',
    collaborationType: 'sponsored_post',
    platform: 'instagram',
    basePriceEur: 1200,
    platformFeeEur: 180,
    totalEur: 1380,
    status: 'in_production',
    brief: 'Create a 45s authentic evening skincare routine featuring our new Botanical Barrier Recovery Cream. Highlight natural scent and glass-skin glow.',
    requirements: [
      'Show bottle clearly in first 5 seconds',
      'Mention 100% cold-pressed rosehip seed extract',
      'Include exclusive discount code AURASOPHIE in caption',
    ],
    deadlineDate: '2026-03-28',
    createdAt: '2026-03-18',
    escrowFunded: true,
    escrowReleased: false,
    deliverables: [],
    messages: [
      {
        id: 'msg-1',
        senderId: 'user_brand_01',
        senderName: 'Elena (Aura Skincare)',
        senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=100&q=80',
        senderRole: 'brand',
        text: 'Hi Sophie! We are thrilled to partner with you. The PR package was delivered to your LA address yesterday.',
        timestamp: 'March 18, 10:15 AM',
      },
      {
        id: 'msg-2',
        senderId: 'creator-01',
        senderName: 'Sophie Kim',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80',
        senderRole: 'creator',
        text: 'Got the package! The texture is gorgeous. I am filming the routine draft tomorrow afternoon.',
        timestamp: 'March 18, 11:30 AM',
      },
    ],
  },
  {
    id: 'ord-102',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=100&q=80',
    creatorId: 'creator-01',
    creatorName: 'Sophie Kim',
    creatorHandle: '@sophiekim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Organic UGC Ad Creative Pack',
    collaborationType: 'content_creation',
    platform: 'ugc',
    basePriceEur: 650,
    platformFeeEur: 97.5,
    totalEur: 747.5,
    status: 'deliverable_submitted',
    brief: 'Two 9:16 vertical hook variations testing "I stopped using foundation" vs "The only serum my dermatologist approved". Raw 4K files for Meta ad campaigns.',
    requirements: [
      'Hook variation 1: 0-3s bold statement with product in frame',
      'Hook variation 2: Natural bathroom mirror lighting demonstration',
      'Clean audio without background noise',
    ],
    deadlineDate: '2026-03-24',
    createdAt: '2026-03-14',
    escrowFunded: true,
    escrowReleased: false,
    deliverables: [
      {
        id: 'del-1',
        title: 'Hook_A_Serum_Routine_4K.mp4',
        previewUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
        submittedAt: 'March 19, 2026',
        notes: 'Filmed in 4K ProRes. Includes text safe zones for Instagram Reels and TikTok ads.',
      },
      {
        id: 'del-2',
        title: 'Hook_B_Bathroom_Mirror_4K.mp4',
        previewUrl: 'https://images.unsplash.com/photo-1608248597359-53530f2955cf?auto=format&fit=crop&w=600&q=80',
        submittedAt: 'March 19, 2026',
        notes: 'Alternative hook focusing on immediate glow effect.',
      },
    ],
    messages: [],
  },
  {
    id: 'ord-103',
    brandId: 'user_brand_01',
    brandName: 'Aura Skincare Paris',
    brandLogo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=100&q=80',
    creatorId: 'creator-02',
    creatorName: 'Liam Carter',
    creatorHandle: '@liamcarter',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    packageTitle: 'Cinematic Reel',
    collaborationType: 'sponsored_post',
    platform: 'instagram',
    basePriceEur: 1400,
    platformFeeEur: 210,
    totalEur: 1610,
    status: 'completed',
    brief: 'Showcasing our travel-size SPF 50 mineral mist during a Dolomites sunrise hike.',
    requirements: ['Show application during mountain summit view'],
    deadlineDate: '2026-03-10',
    createdAt: '2026-02-28',
    escrowFunded: true,
    escrowReleased: true,
    deliverables: [
      {
        id: 'del-3',
        title: 'Dolomites_Sunrise_SPF50_Live.mp4',
        livePostUrl: 'https://instagram.com/p/example',
        submittedAt: 'March 08, 2026',
      },
    ],
    messages: [],
    reviewSubmitted: {
      rating: 5,
      comment: 'Breathtaking footage! Liam is a true cinema professional.',
      date: 'March 10, 2026',
    },
  },
];

export const CATEGORIES_LIST = [
  { id: 'all', name: 'All Creators', count: 12430, icon: 'Grid' },
  { id: 'Beauty', name: 'Beauty', count: 1240, icon: 'Sparkles' },
  { id: 'Fashion', name: 'Fashion', count: 980, icon: 'Shirt' },
  { id: 'Fitness & Health', name: 'Fitness & Health', count: 1340, icon: 'Activity' },
  { id: 'Travel', name: 'Travel', count: 1120, icon: 'Compass' },
  { id: 'Food & Cuisine', name: 'Food & Cuisine', count: 890, icon: 'Utensils' },
  { id: 'Lifestyle', name: 'Lifestyle', count: 1560, icon: 'Coffee' },
  { id: 'Tech & Gaming', name: 'Tech & Gaming', count: 760, icon: 'Laptop' },
  { id: 'Business', name: 'Business', count: 420, icon: 'Briefcase' },
  { id: 'Art & Creativity', name: 'Art & Creativity', count: 680, icon: 'Palette' },
];

export const FAQS_LIST = [
  {
    q: 'How does pricing work on Influverse?',
    a: 'Creators set their own transparent base package prices (in EUR). When a Brand places an order or sends an offer, a 15% platform fee is added (e.g. €100 creator price + €15 platform fee = €115 total before applicable tax). There are no monthly subscription tiers or hidden charges.',
  },
  {
    q: 'What is the difference between Content Creation and Sponsored Posting?',
    a: 'Content Creation (UGC) provides raw, high-quality media assets for the brand to use across its own paid ads, website, and organic channels without requiring the creator to post on their personal feed. Sponsored Posting includes content published directly on the creator’s verified social channel to their engaged audience.',
  },
  {
    q: 'How are payments protected through Escrow?',
    a: 'When an offer is agreed upon, the brand funds the total order amount into secure escrow. The funds are held safely until the creator submits the final deliverables and the brand reviews and approves them. Once approved, the creator base price is instantly disbursed to their wallet.',
  },
  {
    q: 'Can brands request revisions?',
    a: 'Yes. Every package specifies the number of included revisions (typically 1 to 2). Brands can review draft previews in the dedicated order workspace and request tweaks before final approval.',
  },
  {
    q: 'How do creators get discovered and paid?',
    a: 'Creators create a free verified profile, showcase their packages and portfolio, and receive direct hire offers from global brands. Earnings are paid directly in EUR upon job completion.',
  },
];
